### ISSUE TITLE
getter not found 'AVERAGE' 

### ISSUE THREAD

**Issue by sm9i** [fluttercommunity/flutter_launcher_icons#102]

**Comment by sm9i** [comment]
is:issue GGetter not found 'AVERAGE'

**Comment by castrojr913** [comment]
The same thing

**Comment by sm9i** [comment]
> 同一件事情

I found the problem. It's the image library version problem.

You can navigate to image - > SRC - > util - > interpolation. dart and find that it's lowercase and you have to change the image version.

You can modify image version 2.0.7 in'pubspec. lock'.

**Comment by sm9i** [comment]
I found the problem. It's the image library version problem.

You can navigate to image - > SRC - > util - > interpolation. dart and find that it's lowercase and you have to change the image version.

You can modify image version 2.0.7 in'pubspec. lock'.

**Comment by tanutapi** [comment]
Confirm that lower `image` lib version in `pubspec.lock` to `2.0.7` works.

**Comment by maxlapides** [comment]
Because `pubspec.lock` isn't meant to be edited manually, I think the best temporary workaround is to add this to your `pubspec.yaml` file:

```
dependency_overrides:
  image: 2.0.7
```

**Comment by geminiyellow** [comment]
same error here. 

thanks @maxlapides , your comment is right,
and the latest `2.1.0` not working.

**Comment by eniserkaya** [comment]
i have same issue.  dependency_overrides:
  image: 2.0.7 this is work but it must be more good solution for this.

**Comment by MarkOSullivan94** [comment]
Should be fixed in v0.7.1 which I just published tonight 🤞
