### ISSUE TITLE
Failed to precompile flutter_launcher_icons:main:

### ISSUE THREAD

**Issue by otboss** [fluttercommunity/flutter_launcher_icons#104]
Good day to all! 
I tried running the flutter launcher icons plugin as instructed however I receive the following errors:

`
Failed to precompile flutter_launcher_icons:main:
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:207:45: Error: Getter not found: 'AVERAGE'.
    newFile = copyResize(image, e.size, -1, AVERAGE);
                                            ^^^^^^^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:207:25: Error: Too many positional arguments: 1 allowed, but 4 found.
Try removing the extra positional arguments.
    newFile = copyResize(image, e.size, -1, AVERAGE);
                        ^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.0/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,
      ^^^^^^^^^^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:209:45: Error: Getter not found: 'LINEAR'.
    newFile = copyResize(image, e.size, -1, LINEAR);
                                            ^^^^^^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:209:25: Error: Too many positional arguments: 1 allowed, but 4 found.
Try removing the extra positional arguments.
    newFile = copyResize(image, e.size, -1, LINEAR);
                        ^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.0/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,
      ^^^^^^^^^^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:223:63: Error: Getter not found: 'AVERAGE'.
    newFile = copyResize(image, template.size, template.size, AVERAGE);
                                                              ^^^^^^^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:223:25: Error: Too many positional arguments: 1 allowed, but 4 found.
Try removing the extra positional arguments.
    newFile = copyResize(image, template.size, template.size, AVERAGE);
                        ^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.0/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,
      ^^^^^^^^^^
file:///home/otto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:226:63: Error: Getter not found: 'LINEAR'.
    newFile = copyResize(image, template.size, template.size, LINEAR);
                                                              ^^^^^^
pub finished with exit code 1
`

Sorry about the unformatted code

**Comment by dimiandre** [comment]
Same thing here

`MacBook-Pro-di-Andrea:repico_app dimiandre$ flutter packages pub run flutter_launcher_icons:main
Failed to precompile flutter_launcher_icons:main:
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:207:45: Error: Getter not found: 'AVERAGE'.
    newFile = copyResize(image, e.size, -1, AVERAGE);
                                            ^^^^^^^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:207:25: Error: Too many positional arguments: 1 allowed, but 4 found.
Try removing the extra positional arguments.
    newFile = copyResize(image, e.size, -1, AVERAGE);
                        ^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.0/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,
      ^^^^^^^^^^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:209:45: Error: Getter not found: 'LINEAR'.
    newFile = copyResize(image, e.size, -1, LINEAR);
                                            ^^^^^^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:209:25: Error: Too many positional arguments: 1 allowed, but 4 found.
Try removing the extra positional arguments.
    newFile = copyResize(image, e.size, -1, LINEAR);
                        ^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.0/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,
      ^^^^^^^^^^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:223:63: Error: Getter not found: 'AVERAGE'.
    newFile = copyResize(image, template.size, template.size, AVERAGE);
                                                              ^^^^^^^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:223:25: Error: Too many positional arguments: 1 allowed, but 4 found.
Try removing the extra positional arguments.
    newFile = copyResize(image, template.size, template.size, AVERAGE);
                        ^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.0/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,
      ^^^^^^^^^^
file:///Users/dimiandre/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/lib/android.dart:226:63: Error: Getter not found: 'LINEAR'.
    newFile = copyResize(image, template.size, template.size, LINEAR);
                                                              ^^^^^^`

**Comment by subhadipPal** [comment]
[https://github.com/fluttercommunity/flutter_launcher_icons/issues/102](url)

```
dependency_overrides:
  image: 2.0.7
```
worked for me

**Comment by otboss** [comment]
https://github.com/fluttercommunity/flutter_launcher_icons/issues/104#issuecomment-493692563
Thank You, this worked for me also!

**Comment by WeiGrand** [comment]
> [https://github.com/fluttercommunity/flutter_launcher_icons/issues/102](url)
> 
> ```
> dependency_overrides:
>   image: 2.0.7
> ```
> 
> worked for me

+1
