### ISSUE TITLE
plugin 7.2 has same error - Interpolation.average

### ISSUE THREAD

**Issue by NTMS2017** [fluttercommunity/flutter_launcher_icons#109]
User-MBP:my_app useruser$ 
User-MBP:my_app useruser$ flutter packages get                                                    
Running "flutter packages get" in my_app...                  1,6s
User-MBP:my_app useruser$ flutter packages pub run flutter_launcher_icons:main
Failed to precompile flutter_launcher_icons:main:
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:219:82: Error: Getter not found: 'Interpolation'.
    newFile = copyResize(image, width: template.size, height: -1, interpolation: Interpolation.average);
                                                                                 ^^^^^^^^^^^^^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:219:25: Error: Too few positional arguments: 2 required, 1 given.
    newFile = copyResize(image, width: template.size, height: -1, interpolation: Interpolation.average);
                        ^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.7/lib/src/transform/copy_resize.dart:16:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, int width, [int height = -1,
      ^^^^^^^^^^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:221:82: Error: Getter not found: 'Interpolation'.
    newFile = copyResize(image, width: template.size, height: -1, interpolation: Interpolation.linear);
                                                                                 ^^^^^^^^^^^^^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:221:25: Error: Too few positional arguments: 2 required, 1 given.
    newFile = copyResize(image, width: template.size, height: -1, interpolation: Interpolation.linear);
                        ^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.7/lib/src/transform/copy_resize.dart:16:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, int width, [int height = -1,
      ^^^^^^^^^^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:236:93: Error: Getter not found: 'Interpolation'.
    newFile = copyResize(image, width: template.size, height: template.size, interpolation: Interpolation.average);
                                                                                            ^^^^^^^^^^^^^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:236:25: Error: Too few positional arguments: 2 required, 1 given.
    newFile = copyResize(image, width: template.size, height: template.size, interpolation: Interpolation.average);
                        ^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.7/lib/src/transform/copy_resize.dart:16:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, int width, [int height = -1,
      ^^^^^^^^^^
file:///users/useruser/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.2/lib/android.dart:238:93: Error: Getter not found: 'Interpolation'.
    newFile = copyResize(image, width: template.size, height: template.size, interpolation: Interpolation.linear);
                                                                                            ^^^^^^^^^^^^^
pub finished with exit code 1

**Comment by richgoldmd** [comment]
@NTMS2017 I believe this is happening because you still have the dependency override for the image package:
```
dependency_overrides:
  image: 2.0.7
```
This can/should be removed when using the latest package as this issue has been corrected.
