### ISSUE TITLE
Merge flavors with master branch

### ISSUE THREAD

**Issue by robinbonnes** [fluttercommunity/flutter_launcher_icons#114]
Can we merge the flavors branch with the master branch? So I can keep using the flavors branch without dart errors.

**Comment by MarkOSullivan94** [comment]
Merged into flavors branch for now - wanting to get an example project with flavors included before merging into master.

**Comment by MarkOSullivan94** [comment]
Related: https://github.com/fluttercommunity/flutter_launcher_icons/issues/130

Will leave this to someone else who has experience with setting up a Flutter project with flavours enabled
