### ISSUE TITLE
CLI does not create Contents.json for IOS

### ISSUE THREAD

**Issue by stefan-kolb** [fluttercommunity/flutter_launcher_icons#117]
flutter_launcher_icons `^1.7.2+1` does not create a Contents.json when running `flutter packages pub run flutter_launcher_icons:main`.

**Comment by fryette** [comment]
Any plans to fix it?

**Comment by johannphilippe** [comment]
Hi ! I just made a ruby script that will generate the Contents.json lines. 
You just have to copy the code in a ruby file inside Appicon.appiconset folder, and run it from there (ruby myscript.rb) . It will print json to the console, and you just have to copy it to Contents.json file. 

`require "json"

reg = /(?:Icon-App-([0-9]+\.?[0-9]?)x[0-9]+\.?[0-9]?+@([0-9])x\.png)/

hash = Hash.new
hash["images"] = Array.new

Dir.entries(".").each do |entry|
	puts entry	
	if match = entry.match(reg) then
		size, idx = match.captures
	item = Hash.new
	item["size"] = size.to_s + "x" + size.to_s
	item["filename"] = entry
	item["scale"] = idx.to_s + "x"
	item["idiom"] = "iphone"

	hash["images"].push(item)
	end
	
end

puts JSON.pretty_generate(hash)
`

**Comment by valishah** [comment]
Any fix is in place for this? It seems with the latest versions also we have the same problem.

**Comment by charleshan** [comment]
I ran across the same issue. For those of you who are looking for a temporary solution, you can copy the `Contents.json` files from the example directory: 
https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json

**Comment by Cortrano** [comment]
For generation contents.json i uses this guy fork (found on network graph): https://github.com/karer/flutter_launcher_icons/commit/89c99d97a458130efa93459ab27933f37a64b43d

He just wrote one more line of code, please fix it on head repo!

**Comment by RyosukeOK** [comment]
```Contents.json``` file had already been moved.
https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/default/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json

**Comment by L3odr0id** [comment]
[This](https://github.com/fluttercommunity/flutter_launcher_icons/issues/221#issuecomment-1150707790) is a way to overwrite contents.json for ios.
