### ISSUE TITLE
Web Icons

### ISSUE THREAD

**Issue by LCostaN** [fluttercommunity/flutter_launcher_icons#126]
This is half a question and possible an issue so I might be deleting it soon.

### Feature Request

**Add Icon for WEB**
Since Flutter 1.9 web development with flutter, though not yet recommended for production, is getting more and more usual.

So if it's possible I think it would be nice to have this plugin also have an option for browsers and (being a little ahead of time) pwa icon options(1x, 2x, 4x etc.). But PWA is still a thing for later, so the issue is really **asking to have an option for web icon**.

Thank you

**Comment by davidlahuta** [comment]
Now with flutter 1.12, this feature would be really helpful. Any plans?

**Comment by bean5** [comment]
I was really hoping this package would support generating favicons because I have no idea where to place the favicon. I have a work-around, but I doubt it is best practice.

**Comment by personalizedrefrigerator** [comment]
See pull request https://github.com/fluttercommunity/flutter_launcher_icons/pull/155

**Comment by bean5** [comment]
@slightfoot can you close this? It is a duplicate.

**Comment by bean5** [comment]
@slightfoot is there an ETA on this? A cursory view of the PR itself looks like it is more ready than ever.

**Comment by ammaratef45** [comment]
Having this would be great actually

**Comment by bean5** [comment]
@Abhishek0116 do you know what blocks this from being completed?

**Comment by qbait** [comment]
Any update on that one guys?

**Comment by he0119** [comment]
Flutter 2 is released. Any updates on this?

**Comment by Joseph-Nathan** [comment]
any new news ?

**Comment by LostInDarkMath** [comment]
Any plans when web support will be available?

**Comment by AlmogRnD** [comment]
Following

**Comment by EskAere** [comment]
Following

**Comment by nipunasudha** [comment]
Any update? Feels like this is an extremely crucial & relevant feature. Thanks.

**Comment by RatakondalaArun** [comment]
This feature is added in #374
