### ISSUE TITLE
Add support for MacOS

### ISSUE THREAD

**Issue by albertpeiro** [fluttercommunity/flutter_launcher_icons#140]
Hi there, 

First thank you for this awesome tool, it works really well!
I'm supporting macos and would love to see support for this platform as well.

Please let me know if this would be possible and if you need help to implement this.

Thank you.

**Comment by enricobenedos** [comment]
There is also a ready [PR](https://github.com/fluttercommunity/flutter_launcher_icons/pull/189#issue-463290359)

**Comment by 12people** [comment]
Any movement on this?

**Comment by yasinarik** [comment]
When will there a MacOS version?

**Comment by felipecastrosales** [comment]
We need news on this, it will be very important for us 😄🙏

**Comment by MarkOSullivan94** [comment]
MacOS support has been added in this PR: https://github.com/fluttercommunity/flutter_launcher_icons/pull/407
