### ISSUE TITLE
New Icon not change in recent App

### ISSUE THREAD

**Issue by zgramming** [fluttercommunity/flutter_launcher_icons#145]
I have some bug in your package, So today i create new launcher icon with your package. But icon in recent App not updated with new Icon .
I trying in Debug Mode.
### New Icon
![new icon_LI](https://user-images.githubusercontent.com/38829404/71394632-fb104300-2644-11ea-87db-5f45a6116e97.jpg)

### Old Icon in recent App 
![old icon_LI](https://user-images.githubusercontent.com/38829404/71394633-fcda0680-2644-11ea-8f75-f78cc204e207.jpg)

**Comment by sharath12345678** [comment]
Same here,

**Comment by aatmmr** [comment]
Have you removed the app from your device before starting the debug with the new icon set? You can also try to run `flutter clean` staring a new debug session.

**Comment by ThinkDigitalSoftware** [comment]
I'm having this issue in iOS, even after uninstalling, running flutter clean and reinstalling.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-28 at 15 02 45](https://user-images.githubusercontent.com/23037821/73315937-56a29300-41e6-11ea-9117-5f557130414c.png)
<img width="1512" alt="Screen Shot 2020-01-28 at 3 02 58 PM" src="https://user-images.githubusercontent.com/23037821/73315938-56a29300-41e6-11ea-9357-a1aa3e5fd344.png">

**Comment by zgramming** [comment]
Sorry not see this issue notice, After uninstall app it's work

**Comment by ThinkDigitalSoftware** [comment]
> Sorry not see this issue notice, After uninstall app it's work

Ok, that's good information. Thanks. It works on a new device. Not sure what it is.
