### ISSUE TITLE
Integration with build

### ISSUE THREAD

**Issue by dotdoom** [fluttercommunity/flutter_launcher_icons#150]
[build](https://pub.dev/packages/build) offers a platform to perform code generation and other build related tasks. For example, it's used by `built_value` package to generate code.

The beauty of using `build` is that it's a single point of entry to generate artifacts necessary to compile and build a project, which simplifies CI/CD or manual work by offering a single interface.

If this package will integrate with build graph, it would build icons as a part of `pub run build_runner build` or even automatically at compile time via less known [`flutter generate`](https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter)

**Comment by MarkOSullivan94** [comment]
I'd recommend adopting [melos](https://melos.invertase.dev/) if you want to use `flutter_launcher_icons` into your CI / CD pipeline
