### ISSUE TITLE
iOS task manager icon not updating

### ISSUE THREAD

**Issue by lukepighetti** [fluttercommunity/flutter_launcher_icons#156]
We've been using `flutter_launcher_icons` with excellent results, however we have found that the task manager icon does not update anymore. This may not be an issue with `flutter_launcher_icons`, but any help in diagnosing the issue would be appreciated.

![IMG_5B3AFCB92CC1-1](https://user-images.githubusercontent.com/666539/75068175-aa8a5a00-54bc-11ea-803c-9bc8b066d0fc.jpg)

**Comment by honkevin** [comment]
Same here, no sure how to solve

**Comment by SowellM** [comment]
I'm was having the same issue on Android with `flutter_launcher_icons: ^0.7.4`. I changed the version to 'flutter_launcher_icons: ^0.7.3' and the correct icon started showing in the Android app switcher.

**Comment by lukepighetti** [comment]
Ours seems to have updated with no discernible reason.

**Comment by dexcell** [comment]
same issue

**Comment by matthewfx** [comment]
+1

**Comment by davihoffmann** [comment]
Same here,
Are you solved it?

**Comment by lukepighetti** [comment]
It seemed to resolve itself naturally. I'm not sure what caused it to resolve.

**Comment by bradyt** [comment]
Oh, it magically resolved itself here. But I have two commits. Be back later after I have time to see if previous commit still reproduces issue.

**Comment by lukepighetti** [comment]
At this point I'm just assuming on iOS it caches the icon for a couple days or a couple builds. Not sure.

**Comment by bradyt** [comment]
I'm not sure I tested this perfectly, but my impression now is that restarting the phone fixes it, while `git clean -dffx` does not. I may have had other changes between commits that made my tests imperfect. And in the end... who knows.

**Comment by lukepighetti** [comment]
Yeah if we can't pin it down it's not the maintainer of flutter_launcher_icons's responsibility to fool around with it imo

**Comment by peterlauri** [comment]
Restarting the phone resolved it, to not problem with this package 👍

**Comment by cutzmf** [comment]
Device restart solves issue

**Comment by kokocooler2020** [comment]
> Device restart solves issue

YES! me too, on iOS14.
