### ISSUE TITLE
Android round icon support

### ISSUE THREAD

**Issue by TheMisir** [fluttercommunity/flutter_launcher_icons#157]

**Comment by comm1x** [comment]
To support round icons you should also specify `adaptive_icon_background` and `adaptive_icon_foreground` properties.

For `adaptive_icon_background` you can just set background color of your icon, e.g. '#ffffff'

To make image for `adaptive_icon_foreground` from your origin icon, you can use the command:

`convert origin.png -resize 512x512 -gravity center -background transparent -extent 860x860 adaptive.png`

And finally config looks like:

```
image_path: "icon/origin.png"
adaptive_icon_background: '#ffffff'
adaptive_icon_foreground "icon/adaptive.png
```

I hope, it will be automated by library too.

**Comment by TheMisir** [comment]
Thanks, I solved the issue but forgot to close I'm sorry.

**Comment by deadsoul44** [comment]
@comm1x this command is not working for me. It says invalid parameter resize. What do I need to setup to use this command? Thank you.

**Comment by deadsoul44** [comment]
I found it. That command is available on Linux. For windows, I downloaded a similar command line tool called magick. Thank you.

**Comment by deep01code** [comment]
> To support round icons you should also specify `adaptive_icon_background` and `adaptive_icon_foreground` properties.
> 
> For `adaptive_icon_background` you can just set background color of your icon, e.g. '#ffffff'
> 
> To make image for `adaptive_icon_foreground` from your origin icon, you can use the command:
> 
> `convert origin.png -resize 512x512 -gravity center -background transparent -extent 860x860 adaptive.png`
> 
> And finally config looks like:
> 
> ```
> image_path: "icon/origin.png"
> adaptive_icon_background: '#ffffff'
> adaptive_icon_foreground "icon/adaptive.png
> ```
> 
> I hope, it will be automated by library too.

that information should be added to the readme file

**Comment by haoyuant** [comment]
@deep01code Hi, could you tell me how to get this command?
