### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by sagar98cyber** [fluttercommunity/flutter_launcher_icons#158]
![image](https://user-images.githubusercontent.com/57261622/78073557-c0921100-73be-11ea-9d91-fe994659b7fe.png)
 I did exactly what you did with a few details changed does not work

**Comment by Alliiiii** [comment]
Could not find package "flutter_launcher_icons". Did you forget to add a dependency?
pub finished with exit code 65

**Comment by sagar98cyber** [comment]
> Could not find package "flutter_launcher_icons". Did you forget to add a dependency?
> pub finished with exit code 65

No oo I did
