### ISSUE TITLE
Failure for iOS: FileSystemException: Cannot open file

### ISSUE THREAD

**Issue by andcea** [fluttercommunity/flutter_launcher_icons#161]
I've tried running the tool for the first time for iOS and I get
```
flutter pub run flutter_launcher_icons:main
Android minSdkVersion = 16
Creating default icons Android
Overwriting the default Android launcher icon with a new icon
Overwriting default iOS launcher icon with new icon
FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png' (OS Error: No such file or directory, errno = 2)
pub finished with exit code 2
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.0)
[✓] Connected device (4 available)

• No issues found!
```
`flutter_launcher_icons: ^0.7.4`

It seems I'm not the only one: https://github.com/fluttercommunity/flutter_launcher_icons/issues/10#issuecomment-614685889

Previously I've used another tool to generate iOS icons and that used a different path: `ios/Runner/Assets.xcassets/iOS/AppIcon.appiconset` (note the extra iOS directory)

I've fixed the problem by deleting it and reverting to the original flutter generated one but I think this tool should probably be resilient to this situation, or document that it expects the structure that flutter originally generates (maybe it already does).

**Comment by tahan1** [comment]
I have the exact same issue !


```
Android minSdkVersion = 18
Creating default icons Android
Adding a new Android launcher icon
Overwriting default iOS launcher icon with new icon
FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png' (OS Error: Permission denied, errno = 13)
pub finished with exit code 2

**Comment by eliabieri** [comment]
Me too

```
Overwriting default iOS launcher icon with new icon
FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png' (OS Error: No such file or directory, errno = 2)
```

**Comment by tahan1** [comment]
In the meanwhile, I went with this solution: https://stackoverflow.com/a/55054303/4865751 manually updating the icons...

**Comment by zacwillis** [comment]
Me too

Android minSdkVersion = 16
Creating default icons Android
Overwriting the default Android launcher icon with a new icon
Overwriting default iOS launcher icon with new icon
FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png' (OS Error: Permission denied, errno = 13)

**Comment by RahmatAliMalik5** [comment]
Try to check the file path you provided. I have the same issue and I was providing wrong file path. I was using `icon` instead of `icons` in my path list. Like:

I was using before and able to see the error:
`assets/icon/icon_result.png`

my files original path:
`assets/icons/icon_result.png`

**Comment by paulblyth** [comment]
> Me too
> 
> Android minSdkVersion = 16
> Creating default icons Android
> Overwriting the default Android launcher icon with a new icon
> Overwriting default iOS launcher icon with new icon
> FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png' (OS Error: Permission denied, errno = 13)

I'm having the same problem as you - note the error is slightly different. Bizarrely I can get it working with a simple screenshot on my mac, but the actual image I want to use causes problems. Having resized the image I did get some images to generate but still couldn't get the full set to work. Perhaps you might have more luck!

**Comment by craigjwallace** [comment]
Same. Android Studio 4 on windows 10

Android minSdkVersion = 16
Creating default icons Android
FileSystemException: Cannot open file, path = 'assets/images/app_icon.png' (OS Error: The system cannot find the path specified.
, errno = 3)

Double, triple checked for typos etc.

**Comment by DustinJSilk** [comment]
Gah this is so annoying. works fine with Android but iOS doesn't

**Comment by craigjwallace** [comment]
on ios the path (to the icons) might be relative to a different place -- eg the project root folder?

**Comment by tamoyal** [comment]
I came across this issue because I deleted my AppIcon before generating the new one. Then when I saw this issue, I added a new "image set" and called it AppIcon, however that is also wrong. You have to add a new 
![Uploading Screen Shot 2020-12-15 at 2.52.14 PM.png…](iOS app icon) which is a special type of asset in the bundle.

**Comment by jonchui** [comment]
I did the same @tamoyal . I deleted the default `flutter` `AppIcon` set and created my own blank one, then re-ran the command: `flutter pub run flutter_launcher_icons:main` and it seemed to work. 

However, when i re-opened the flutter app in xcode, it looks like all the generated icons are "unassigned":

![image](https://user-images.githubusercontent.com/204868/106640431-46cd3580-6543-11eb-9b6a-5e2b38ea625f.png)

Then, the icon doesn't work in the simualator:

![Uploading image.png…]()


Does anyone else see this issue?

**Comment by afzl-wtu** [comment]
Simple Solution: Run : flutter create .
in Project Directory and you are done. Now you can use launcher icon package freely.

**Comment by benjaminudoh10** [comment]
You may need to add `lib` to the path name. This was what worked for me.

`flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  adaptive_icon_background: "#C77DFF"`

**Comment by arballogerardo** [comment]
> 

it worked for me

**Comment by Heech** [comment]
> FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/[Icon-App-29x29@1x.png](mailto:Icon-App-29x29@1x.png)' (OS Error: Permission denied, errno = 13)

Had a similar error to this when trying to use a png image exported from figma.
For some reason re-exporting the same image and trying again somehow solved it.
I think the error might be misleading but not really sure what the cause was.

**Comment by Namr547** [comment]
The issue arises from the configuration in your flutter_launcher_icons settings:

```

    flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      image_path: "assets/icon/icon.png"
```

  
  If you create a Flutter project without selecting iOS support and only choose Android, setting **ios: true** will lead to an error.
  
 *To fix the issue:*
**Remove the line ios: true from your configuration.**

After making this change, the error should go away.
