### ISSUE TITLE
Doesn't even work

### ISSUE THREAD

**Issue by shane99a** [fluttercommunity/flutter_launcher_icons#164]
```
flutter_icons:
    android: true,
    ios: true,
    image_path: "assets/icon.png"
```

```
Android minSdkVersion = 16
Creating default icons Android
Adding a new Android launcher icon
*** ERROR ***
InvalidAndroidIconNameException
The icon name must contain only lowercase a-z, 0-9, or underscore: E.g. "ic_my_new_icon"
pub finished with exit code 2
```

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Linux, locale C.UTF-8)
    • Flutter version 1.17.0-3.2.pre at /home/user/flutter
    • Framework revision 2a7bc389f2 (4 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)
```

**Comment by tomasbaran** [comment]
Maybe it's because you use commas at the end of lines. It should be like this:

```
flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon.png"
```

**Comment by goherhussain** [comment]
I have already done this but its still not working for me. Here's my yaml file

name: flutterapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.7.5"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - images/diamond.png
    - images/ic_launcher.png

**Comment by goherhussain** [comment]
I just note now. I ran it on two different devices.
1) On Samsung device its working fine 
2)On Vivo1832 its showing default flutter icon

**Comment by ride4sun** [comment]
try to indent the flutter_icons and children

**Comment by jogindergur** [comment]
I'm also facing issue with Vivo mobile. I have checked that the flutter_launcher_icons updated ic_launcher icon but changes are not reflected in the mobile. I have tried the flutter clean, fresh install and try to make a release version instead of debug. Still icon is there. No idea why

**Comment by RKiranKumarReddy010** [comment]
> I'm also facing issue with Vivo mobile. I have checked that the flutter_launcher_icons updated ic_launcher icon but changes are not reflected in the mobile. I have tried the flutter clean, fresh install and try to make a release version instead of debug. Still icon is there. No idea why

I am also facing the same issue idk how to solve this....
