### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RaulBarrada1** [fluttercommunity/flutter_launcher_icons#168]
### :information_source: Info
Version: `e.g. v0.7.5`

### :speech_balloon: Description
When inserting code:

dependencies:
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_icons:
    android: "launcher_icon" # or true 
    ios: true
    image_path: "assets/icon/icon.png" #path correct

 the application gives an error when executing "pub get".

ERROR_BEGIN

Error on line 39, column 5 of pubspec.yaml: A dependency may only have one source.
   ╷
39 │ ┌     android: "launcher_icon"
40 │ │     ios: true
41 │ │     image_path: "assets/icon/icon.png"
42 │ │ 
43 │ │   flutter_test:
   │ └──^
   ╵
pub get failed (65;    ╵)

ERROR_END

![Capturar](https://user-images.githubusercontent.com/20230101/81626725-e73a6300-93d2-11ea-87f0-470d8d1a751d.PNG)

**Comment by pestorius** [comment]
Are your dependencies properly indented? I get the same error when they're not.

Here's an example that works for me

<img width="251" alt="Screenshot 2020-05-12 at 6 17 55 PM" src="https://user-images.githubusercontent.com/21284418/81673136-bb27ec00-947d-11ea-961a-3aaca2e3e31a.png">

**Comment by RaulBarrada1** [comment]
Thank you, the error was in a tab in front of the command flutter_icons. :)
