### ISSUE TITLE
pub finished with exit code 65[BUG] 

### ISSUE THREAD

**Issue by JayChiD** [fluttercommunity/flutter_launcher_icons#170]
flutter_launcher_icons: ^0.7.5

When I try to run $flutter pub run flutter_launcher_icons:main

returns : Waiting for another flutter command to release the startup lock...
Could not find package "flutter_launcher_icons". Did you forget to add a dependency?
pub finished with exit code 65
![Screen Shot 2020-05-16 at 6 25 37 pm](https://user-images.githubusercontent.com/54469850/82114941-0f470f00-97a3-11ea-9a9f-7b3e13ea7097.png)

**Comment by abdalmonem** [comment]
Often you are on 2.7 dart version , are you ?

**Comment by DenisMrGnusa** [comment]
> Often you are on 2.7 dart version , if your app working on any dart version 2.7 or upper , please run :
> 
> `flutter pub run flutter_launcher_icons:main`
> 
> @MarkOSullivan94 "Readme" should mention this

I've tried your code, but still the same error...
any suggestion?

**Comment by muratozbayraktar** [comment]
Same error for me

**Comment by alejosantioscar** [comment]
Hola. Tengo el mismo problema. Al ejecutar en terminal flutter pub run flutter_launcher_icons:main me sale el siguiente mensaje: Could not find package "flutter_launcher_icons". Did you forget to add a dependency?
pub finished with exit code 65

Por favor me orientan que puedo hacer

Muchas gracias

adriana

**Comment by alejosantioscar** [comment]
> Lo arreglo. Asista su terminal a la carpeta de su proyecto (donde está pubspec.yaml) y luego ejecute commend.

Hola. Por favor me explica como hacer esto que dices

**Comment by amitw7786** [comment]
I am just a beginner in flutter and
I had the same issue while using `flutter pub run flutter_launcher_icons:main` Command
I overcome it by adding a proper flutter_launcher_icons version... 
In my case needed version was flutter_launcher_icons: ^0.9.0 and it wasn't mentioned before.
So when I add this in devDependencies like :

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.5
  dependency_validator: 3.1.0
  encrypt: ^5.0.0
  flutter_launcher_icons: ^0.9.0

Enable To run json serializer, run:
flutter pub run build_runner build --build-filter="lib/models/serializers/*.dart" --delete-conflicting-outputs
flutter pub run build_runner serve --build-filter="lib/models/serializers/*.dart"
build_runner: 2.0.3
json_serializable: 4.1.2

Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

It Worked for me!!!!
