### ISSUE TITLE
Android version 10 - App icon issue

### ISSUE THREAD

**Issue by truptikate94** [fluttercommunity/flutter_launcher_icons#173]
My app is live on the PlayStore, the app icon is visible for all Android and iOS devices. But when I try to install the app on Android version 10, the app icon is not visible, it shows the default Android app icon.

**Comment by ghenry** [comment]
Did this show in your testing via PlayStore? How did it get live without you noticing this?

**Comment by lautaropaske** [comment]
Seems to be the same issue as #167

**Comment by hussenIbrahim** [comment]
android: true
works for my
