### ISSUE TITLE
[BUG]  FileSystemException: Cannot open file, path = 'assets/launcher/icon.png' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by phongyewtong** [fluttercommunity/flutter_launcher_icons#174]
### :information_source: Info
Version:  v0.7.5

### :speech_balloon: Description

Not sure why it cant find my assets?

```
phongyewtong@Phongs-MBP taskvs % flutter pub run flutter_launcher_icons:main
Android minSdkVersion = 16
Creating default icons Android
FileSystemException: Cannot open file, path = 'assets/launcher/icon.png' (OS Error: No such file or directory, errno = 2)
pub finished with exit code 2
```

### :scroll: Pubspec.yaml

name: project1
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
  flutter_local_notifications: ^1.4.3
  flutter_app_badger: ^1.1.2
  intl: ^0.16.1
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  flutter_auth_buttons: ^0.8.0
  bot_toast: ^3.0.0
  flutter_spinkit: ^4.1.2
  firebase_remote_config: ^0.3.1
  flutter_email_sender: ^3.0.1
  device_info: ^0.4.2+4
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon_bg.png"
  adaptive_icon_foreground: "assets/launcher/icon_fg.png"

flutter:
  assets:
    - assets/launcher/icon.png
    - assets/launcher/icon_bg.png
    - assets/launcher/icon_fg.png

  uses-material-design: true

### :scroll: Flutter doctor -v

[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.2 at /Users/phongyewtong/flutter
    • Framework revision 5f21edf8b6 (3 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/phongyewtong/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • F5B21B90-6245-4BE7-BF06-0F7F2E851172 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by saigkl** [comment]
Can you share how did you resolve this issue?

**Comment by shatanikmahanty** [comment]
Try giving a single space between image_path and original path.

Eg: image_path: "assets/ic_launcher.png"

**Comment by rajesh2701** [comment]
can you please share, how did you resolve this issue?

**Comment by hruuuuu** [comment]
Here's [benjaminudoh10](https://github.com/benjaminudoh10) solution. It worked for me!
https://github.com/fluttercommunity/flutter_launcher_icons/issues/161#issuecomment-870685623
