### ISSUE TITLE
any plans on mac os support?

### ISSUE THREAD

**Issue by softmarshmallow** [fluttercommunity/flutter_launcher_icons#182]
icon generation core is almost identical between ios and macos.
wonder if there is any plans for supporting macos icons generation (same xcassets)

**Comment by hotlittlewhitedog** [comment]
issue already exist: https://github.com/fluttercommunity/flutter_launcher_icons/issues/140

**Comment by hhstore** [comment]
#255 
#334 
#140 
#189

**Comment by RatakondalaArun** [comment]
This issue is tracked in #379
