### ISSUE TITLE
Favicon for Web [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Abhishek0116** [fluttercommunity/flutter_launcher_icons#183]
### :speech_balloon: Description
A favicon for the Web platform.
When and will you develop a favicon for flutter web?
### :question: Platform
Web

**Comment by personalizedrefrigerator** [comment]
See pull request #155!

**Comment by llucax** [comment]
duplicate of #126

**Comment by bean5** [comment]
@slightfoot can you close this? It is a duplicate.

**Comment by Abhishek0116** [comment]
Thank you, guys.

Closing this because it's detected as a duplicate of #126 as @llucax found and also this feature implemented in #155 PR as @personalizedrefrigerator said. He also mentions important notes that favicons will only be generated when building for the web and cannot be seen while testing.
