### ISSUE TITLE
The app icon on android looks box on some devices

### ISSUE THREAD

**Issue by 1996SEJR** [fluttercommunity/flutter_launcher_icons#187]
The app icon on android looks box on some devices (huawei p20, samsing j5)
How to make it fit all devices?

**Comment by tapizquent** [comment]
In Pixel 4 XL. The icon looks like a box (square) inside the rounded icon and does not fit completely.

**Comment by MarkOSullivan94** [comment]
Ensure you have configuration setup to use adaptive icons and this wont be an issue
