### ISSUE TITLE
[QUESTION] - Icon when in background on Android

### ISSUE THREAD

**Issue by brenoasm** [fluttercommunity/flutter_launcher_icons#194]
Hi, I already tried a bunch of things and this Icon doesnt change:

![Screenshot_2020-08-27-14-53-45-614_com.android.systemui.jpg](https://user-images.githubusercontent.com/25211056/91480859-ef32eb80-e879-11ea-9c89-66f8073ec6bb.jpg)

I dont know If that lib should be doing It, If not, Sorry.

Do I need to do something more than the documentation tells?

Thanks in advance.

**Comment by shripalpanchiwala** [comment]
hi
I know how to add icon when in the background on android 
can I join in our project
