### ISSUE TITLE
[BUG] pub finished with exit code 255

### ISSUE THREAD

**Issue by TheWithz** [fluttercommunity/flutter_launcher_icons#196]
### :information_source: Info

Version: `^0.8.0`

### :speech_balloon: Description

running `flutter pub run flutter_launcher_icons:main -f pubspec.yaml`
throws this error
> thewithz@homebase[dev!?] flutter pub run flutter_launcher_icons:main -f pubspec.yaml
Precompiling executable...
Precompiled flutter_launcher_icons:main.
>  ____________________________________________
>     FLUTTER LAUNCHER ICONS (v0.8.0)
>  ____________________________________________

> _ Creating default icons Android
> _ Adding a new Android launcher icon

> _ Successfully generated launcher icons
> Unhandled exception:
> NoSuchMethodError: The getter 'width' was called on null.
> Receiver: null
> Tried calling: width
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      createResizedImage (package:flutter_launcher_icons/utils.dart:4:13)
> #2      saveNewImages (package:flutter_launcher_icons/android.dart:241:25)
> #3      createDefaultIcons (package:flutter_launcher_icons/android.dart:43:7)
> #4      createIconsFromConfig (package:flutter_launcher_icons/main.dart:97:5)
> #5      createIconsFromArguments (package:flutter_launcher_icons/main.dart:56:7)
> #6      main (file:///home/thewithz/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.8.0/bin/main.dart:6:3)
> #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> pub finished with exit code 255

### :scroll: Pubspec.yaml

> environment:
>   sdk: ">=2.7.0 <3.0.0"
> 
> dependencies:
>   flutter_launcher_icons: "^0.8.0"
>   flutter:
>     sdk: flutter
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
> flutter:
>   uses-material-design: true
>   fonts:
>     - family:  GardenPlannerIcons
>       fonts:
>         - asset: fonts/GardenPlannerIcons.ttf
> 
> flutter_icons:
>   android: "launcher_icon"
>   adaptive_icon_background: #FF4CAF50
>   ios: false
>   image_path: "assets/icon/garden_planner.ico"

**Comment by Janaka-Steph** [comment]
I had the same error with svg but not with png. The readme should say which formats are supported.

**Comment by leerasamart** [comment]
Create Folder AppIcon.appiconset in Assets.xcassets and try to run command again

**Comment by TheWithz** [comment]
I solved this by wrapping the hex number in double quotes
before:
`adaptive_icon_background: #FF4CAF50`
after:
`adaptive_icon_background: "#FF4CAF50"`
