### ISSUE TITLE
[FEATURE REQUEST] optimize generated images

### ISSUE THREAD

**Issue by danielgomezrico** [fluttercommunity/flutter_launcher_icons#199]
### :speech_balloon: Description
Thanks for this awesome lib.

After creating all of the icons, I checked if there was some kind of possible image optimizations without loosing quality, and I found that there are more things to be done there.

The idea is that this generates more optimal images.
> We can save like 30-70% on image size per image.

I used a simple app http://imageoptim.com that uses multiple algorithms and optimizations:

![image](https://user-images.githubusercontent.com/76348/94159487-3b595780-fe49-11ea-9bea-afe0be188290.png)

And these are the results:

![image](https://user-images.githubusercontent.com/76348/94159535-47ddb000-fe49-11ea-882f-3d3dd3810fa7.png)

**Comment by mx1up** [comment]
i would suggest `pngcrush` which is readily available on all linux
