### ISSUE TITLE
[FEATURE REQUEST] Windows Icon Support

### ISSUE THREAD

**Issue by msyagami** [fluttercommunity/flutter_launcher_icons#200]
### :speech_balloon: Description
Is there a chance to get a support on Windows? It's kind of tricky to modify it since Flutter replaces it to the old icon.

### :question: Platform
Windows

**Comment by Robert3141** [comment]
I haven't read how to do a flavor however, placing an ```app_icon.ico``` in the folder ```windows\runner\resources\app_icon.ico``` changes the Windows icon. That should be easy to implement right?

**Comment by RatakondalaArun** [comment]
Support for windows icon is added with #380
