### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Psycarlo** [fluttercommunity/flutter_launcher_icons#201]
Version: v^0.8.0

### :speech_balloon: Description
Can't run flutter pub run flutter_launcher_icons:main . I have 3 different flavors yaml files. 
For example this flutter_launcher_icons-dev.yaml : 
`flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/<image-name>.png"`

The error when I run that command: ✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section

When I run flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons-dev.yaml : 

`FileSystemException: Cannot open file, path = 'flutter_launcher_icons-dev.yaml' (OS Error: The system cannot find the file specified.
, errno = 2)

✓ Successfully generated launcher icons
Unhandled exception:
NoSuchMethodError: The method 'containsKey' was called on null.
Receiver: null
Tried calling: containsKey("image_path")` ...

### :scroll: Pubspec.yaml
`name: <app>
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.8.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true`

**Comment by msyagami** [comment]
Try importing your images first on your `pubspec.yaml`:
```
flutter:
  assets:
    - assets/<image_name>
```

(PS: don't forget to create an `assets` directory before inserting the code.) Hope that fixes your issue.

**Comment by Psycarlo** [comment]
The problem with
`flutter_icons:
  android: true
  ios: true
  image_path: "assets/<image-name>.png"`

is that i have 3 different flavors. I want to run `flutter run --flavor {flavor}` and different app icon appear. 
Following the example here: https://github.com/fluttercommunity/flutter_launcher_icons/tree/master/example/flavors

but this error keeps showing:

`✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section
pub finished with exit code 1`

**Comment by Psycarlo** [comment]
Under lib/main.dart on the `flavorConfigFilePattern String` I only get a match on my `flutter_launcher_icons-<>.yaml ` files if I change it to: `'\.\\\\flutter_launcher_icons-(.*).yaml'` instead of `'\./flutter_launcher_icons-(.*).yaml'`. (I'm on Windows).

Can someone verify this?

**Comment by Psycarlo** [comment]
I just copied the `flutter_launcher_icons-<>.yaml` from the fork and paste on my project and they worked...
I don't know why.

You can close this issue I guess.

**Comment by Psycarlo** [comment]
The error `✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section
pub finished with exit code 1`  is being made by this function:
`loadConfigFileFromArgResults(argResults, verbose: true);`
when running: `flutter run pub flutter_launcher_icons:main` when having multiple flavors.

**Comment by sarbogast** [comment]
I confirm. I have the same issues. Flavor support needs to be documented more. I have my 3 flevor-specific YAML files, now which commands should I run to create icons for each flavor? Ideally a single command should create icons for all flavors at once.

**Comment by personalizedrefrigerator** [comment]
I might have fixed this in #155... Would someone be willing to confirm this?

**Comment by Psycarlo** [comment]
`flutter run pub flutter_launcher_icons:main` should run for all flavors. Can't confirm. Still not working for me.

**Comment by jain-aayush1123** [comment]
Any fix found for this? 
Running 
`flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons*`

gives error 
`FileSystemException: Cannot open file, path = 'flutter_launcher_icons*' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
NoSuchMethodError: The method 'containsKey' was called on null.
Receiver: null
Tried calling: containsKey("image_path")
pub finished with exit code 2`

**Comment by jamiul-999** [comment]
Did you fix it?

**Comment by MarkOSullivan94** [comment]
> Ideally a single command should create icons for all flavors at once.

@sarbogast this actually already happens with the original flavors feature implementation, if you specify a config file then it'll automatically look for any other config files you have and run them too

You can try this out in the example project: https://github.com/fluttercommunity/flutter_launcher_icons/tree/master/example/flavors

Instead of running
```
flutter run pub flutter_launcher_icons:main
```

You should run
```
flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons-production.yaml
```

**Comment by MarkOSullivan94** [comment]
> flutter run pub flutter_launcher_icons:main should run for all flavors. Can't confirm. Still not working for me.

I'm not sure I understand @Psycarlo, sorry! 

Do you have flavors enabled in your project and you want to edit your pubspec.yaml file with Flutter Launcher Icons and have it change the icon for all flavors?

**Comment by MarkOSullivan94** [comment]
Also @Psycarlo I'm afraid I don't understand the issue here, would you be able to fork Flutter Launcher Icons and setup the example project so it replicates the issue you're having?

Once you do that I can clone it and run the example to debug what's going wrong

**Comment by EduardoMoreira26** [comment]
`flutter pub run flutter_launcher_icons:main`  instead of `flutter run pub flutter_launcher_icons:main`
