### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by monizj** [fluttercommunity/flutter_launcher_icons#210]
### :information_source: Info

 flutter_launcher_icons: ^0.8.1 

### :speech_balloon: Description
✓ Successfully generated launcher icons
Unhandled exception:
NoSuchMethodError: The method 'endsWith' was called on null.
Receiver: null
Tried calling: endsWith(".png")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      isAdaptiveIconConfigPngFile (package:flutter_launcher_icons/android.dart:309:25)
#2      createAdaptiveIcons (package:flutter_launcher_icons/android.dart:85:7)
#3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:102:5)
#4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:58:7)
#5      main (file:///Users/jonathanmoniz/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.8.1/bin/main.dart:6:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255

Enter a description of your problem here

### :scroll: Pubspec.yaml
name: flutter_app_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
    android: true
    ios: true
    image_path: "dev_assets/places.png"
    adaptive_icon_background: #191919"
    adaptive_icon_foreground: "dev_assets/places-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by personalizedrefrigerator** [comment]
It looks like the issue is the line `adaptive_icon_background: #191919"` in your `pubspec.yaml`. 

I think `#191919 ` is being interpreted as a comment. Make sure it is completely surrounded by double-quotes!
