### ISSUE TITLE
Could not find bin\main.dart in package flutter_launcher_icons. 

### ISSUE THREAD

**Issue by theAkshay60** [fluttercommunity/flutter_launcher_icons#211]
This is what I did in the pubspec.yaml:

Added flutter_launcher_icons: ^0.8.1 dependency.

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bhoomi.jpg"

**Comment by theAkshay60** [comment]
pub finished with exit code 66

**Comment by ricguti** [comment]
Did you run these commands?
```
flutter pub get
flutter pub run flutter_launcher_icons:main
```

**Comment by theAkshay60** [comment]
yes, I did

**Comment by Indy9000** [comment]
same result for me too

**Comment by sagarvd01** [comment]
Having same issue.

**Comment by ratiebareeng** [comment]
I had the same issue and realized I had a space between colon and main. Running the command without the space did it for me.

Failed (space between : main): flutter pub run flutter_launcher_icons: main
Successful (no space): flutter pub run flutter_launcher_icons:main

**Comment by Snave254** [comment]
Thanks @ https://github.com/ratiebareeng
Solved my problem

**Comment by RatakondalaArun** [comment]
Closing this as inactive in case this issue still exists please open a new issue
