### ISSUE TITLE
ERROR ITMS-90717: "Invalid App Store Icon. The App Store Icon in the asset catalog in 'Runner.app' can't be transparent nor contain an alpha channel."

### ISSUE THREAD

**Issue by sidc0des** [fluttercommunity/flutter_launcher_icons#216]
### :information_source: Info

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/ic_launcher.png"

### :speech_balloon: Description

Error while uploading archive to appconnect via xcode

### :scroll: Pubspec.yaml
name: villa_project_screens
description: A new Flutter project.
publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_pro: ^1.0.0
  carousel_slider: ^2.3.1
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.1
  international_phone_input: ^1.0.4
  multi_image_picker: ^4.7.14
  permission_handler: ^5.0.1+1
  pin_entry_text_field: ^0.1.3
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/ic_launcher.png"
flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/lang/ar.json
    - asset/lang/en.json

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by alocus** [comment]
It may not be a problem with the library.  If you can try jpg instead of png, I believe it will solve the problem.  Nonetheless, it may be a good idea to use jpg in the examples or make a note about this in the readme.

**Comment by sidc0des** [comment]
yes my bad
