### ISSUE TITLE
Border added to icons on cheap Android phone

### ISSUE THREAD

**Issue by joshipucher** [fluttercommunity/flutter_launcher_icons#217]
Hello.

The icons created with the plugin worked for me for iOS Emulator, iOS Real Device and also Android Emulator (Pixel 5).

But now I bought a cheap Android phone (Ulefone Note 8P) for testing purposes and the icons look way too small. It looks like a border/padding is added to the icon. How can I fix this?

Thank you

![Screenshot_20201125-165235](https://user-images.githubusercontent.com/65084654/100259242-4b281180-2f48-11eb-92de-7501a6985ffb.png)
![Screenshot_20201125-165258](https://user-images.githubusercontent.com/65084654/100259263-52e7b600-2f48-11eb-88b3-788ed6c5ceb7.png)

**Comment by MarkOSullivan94** [comment]
Are you using adaptive icons or only the launcher icon?
