### ISSUE TITLE
[FEATURE REQUEST] Null safety support?

### ISSUE THREAD

**Issue by KThen** [fluttercommunity/flutter_launcher_icons#230]
### :speech_balloon: Description
Is there any roadmap to support null safety down the line? I am starting to get issues when using this together with the flutter_svg package. Currently I am disabling the dependency on this since I am using it as dev dependency, but I do need flutter_svg for my project. Hope to hear back on thoughts on this.

### :question: Platform
This feature request is not targeted towards specific platform.

**Comment by MarkOSullivan94** [comment]
@SteveAlexander has kindly already done changes to make Flutter Launcher Icons null safe: https://github.com/fluttercommunity/flutter_launcher_icons/pull/229

This has been merged into a separate `null-safety` branch for anyone who wants to use a null safe version before it's in the next release

**Comment by deibeeed** [comment]
Hey!

First of all, thank you for the awesome project. 
Is there a way to update the readme doc to include null-safety? can't `flutter pub get` it. thanks again.

**Comment by nohli** [comment]
@MarkOSullivan94 you could also publish a prerelease version with nullsafety support, as many packages are doing: https://dart.dev/null-safety/migration-guide#step5-publish

Null-safety branch works fine, thank you!

**Comment by MarkOSullivan94** [comment]
@nohli published v0.9.0 last night which contains null-safety support 🎉
