### ISSUE TITLE
[BUG] Resolving Dependencies Fail

### ISSUE THREAD

**Issue by javierbm7** [fluttercommunity/flutter_launcher_icons#236]
### :information_source: Info

Version: `e.g. v0.9.0`

### :speech_balloon: Description

With the new Flutter version not working

Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and encrypt 4.1.0 depends on args ^1.6.0, flutter_launcher_icons >=0.9.0 is incompatible with encrypt 4.1.0.
And because no versions of encrypt match >4.1.0 <5.0.0, flutter_launcher_icons >=0.9.0 is incompatible with encrypt ^4.1.0.
So, because oci_balance_app depends on both encrypt ^4.1.0 and flutter_launcher_icons ^0.9.0, version solving failed.
pub get failed (1; So, because oci_balance_app depends on both encrypt ^4.1.0 and flutter_launcher_icons ^0.9.0, version solving failed.)

### :scroll: Pubspec.yaml

dependencies:
  datetime_picker_formfield:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  string_mask: ^0.1.0
  splashscreen: ^1.3.5
  percent_indicator: ^2.1.9+1
  dynamic_theme: ^1.0.1
  encrypt: ^4.1.0
  rounded_letter: any
  flutter_secure_storage: ^4.0.0
  url_launcher: ^6.0.2
  awesome_dialog: ^1.3.2
  flutter_emoji: ^2.2.1+1
  fl_chart: ^0.20.1
  filter_list: ^0.0.7
  scroll_shadow_container: ^1.0.1
  connectivity_wrapper: ^1.0.4
  vibration: ^1.7.3
  flutter_brand_icons: ^1.1.0
  flutter_counter: ^1.0.3
  flutter_advanced_switch: ^1.0.0+1
  responsive_grid: ^1.2.1+1
  fab_menu_items: ^1.0.0
  clipboard: ^0.1.2+8
  native_webview: ^0.27.0
  sizer: ^1.1.5
  json_table: ^1.4.0
  string_validator: ^0.1.4
  flutter_json_widget: ^1.0.1
  cached_network_image: ^2.5.0
  webfeed: ^0.6.0
  rest_client: ^1.0.6+2
  flutter_launcher_icons: ^0.9.0

`

**Comment by MikeRee** [comment]
Have a similar issue:
Because moor_generator 3.4.1 depends on args ^1.5.0 and no versions of moor_generator match >3.4.1 <4.0.0, moor_generator ^3.4.1 requires args ^1.5.0.
And because flutter_launcher_icons >=0.9.0 depends on args 2.0.0, moor_generator ^3.4.1 is incompatible with flutter_launcher_icons >=0.9.0.
So, because project depends on both moor_generator ^3.4.1 and flutter_launcher_icons ^0.9.0, version solving failed.
pub get failed (1; So, because project depends on both moor_generator ^3.4.1 and flutter_launcher_icons ^0.9.0, version solving failed.)

**Comment by MarkOSullivan94** [comment]
@javierbm7 both the `encrypt` package and `flutter_launcher_icons` package depends on the `args` package but they target different versions.

There's a new version of encrypt which is also using args 2.0.0, if you upgrade encrypt to `5.0.0-beta.1` this should hopefully fix your issue.

@MikeRee similar to the above, `moor_generator` is targeting an earlier version of the `args` package.

I had a quick look at `moor_generator`'s pubspec yaml, it hasn't been updated to use null safe packages but I noticed `moor_flutter` has, perhaps it'd be worthwhile [opening an issue](https://github.com/simolus3/moor/issues) to see if they could update their dependencies for the `moor_generator`?

For now if you add the below line to your pubspec.yaml it should work
```
dependency_overrides:
  args: '2.0.0'
```

Hope this helps both of you 😃

**Comment by MikeRee** [comment]
Thanks, wasn't aware of the dependecy_overrides. Had to use it a few times but managed to get my app working again. Thanks.
