### ISSUE TITLE
[BUG] IOS - on app paused launcher icon remains default

### ISSUE THREAD

**Issue by jan-koz** [fluttercommunity/flutter_launcher_icons#239]
As title says, on IOS when app is paused icon did not change. Problem occurs on the view in which you are able to swipe up app view to make it inactive

**Comment by tokyokamera** [comment]
Restarting the phone resolved it, to not problem with this package

**Comment by timbrueckner** [comment]
This should be mentioned in the docs.

**Comment by MarkOSullivan94** [comment]
> This should be mentioned in the docs.

Feel free to submit a PR @timbrueckner
