### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jaypatel850** [fluttercommunity/flutter_launcher_icons#240]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here
flutter pub get
flutter pub run flutter_launcher_icons:main -f <your config file name here>
 this command when i enter comes flutter is not recognized

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by alexobviously** [comment]
This isn't related to `flutter_launcher_icons`, you probably haven't set up your PATH variable properly. Look at the flutter installation instructions for your OS, it'll have a section explaining how to do it there.
