### ISSUE TITLE
[FEATURE REQUEST] Desktop launcher icon support

### ISSUE THREAD

**Issue by mbalmer** [fluttercommunity/flutter_launcher_icons#242]
### :speech_balloon: Description

Please add support for the desktop Platforms (macOS, Windows, Linux) and Web

### :question: Platform
Web / Mac OS / Windows / Linux

**Comment by tsinis** [comment]
Hey @mbalmer, there are PRs for macOS and Web, you can use them now. Linux icons are not supported in Flutter itself now, there is an open [issue](https://github.com/flutter/flutter/issues/53229). If you need a Windows icon, there is a solution with another tool.

**Comment by RatakondalaArun** [comment]
This issue is being tracked in #379
