### ISSUE TITLE
[FEATURE REQUEST] Desktop documentation not found

### ISSUE THREAD

**Issue by Abhishek0116** [fluttercommunity/flutter_launcher_icons#243]
### :speech_balloon: Description
It looks like you support the desktop platform according to [pub.dev Flutter Launcher Icons](https://pub.dev/packages/flutter_launcher_icons) 

![Screenshot 2021-03-24 at 13 51 47](https://user-images.githubusercontent.com/35359840/112277798-1d5d9a00-8ca8-11eb-81c5-46aea3d59a96.png)

This may be a bug because you did not support the desktop platform actually. Also, documentation not provided for these platforms. So please remove all desktop platform flag until you really support.

### :question: Platform
Is this feature request for a specific platform? E.g.  Mac OS / Windows / Linux

**Comment by kishanhitk** [comment]
@Abhishek0116, thanks for opening the issue, but currently the package does not support desktop.

**Comment by richard457** [comment]
Any plans to support desktops?

**Comment by RatakondalaArun** [comment]
Planning for desktop is tracked in #379
