### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by faheemjavid131** [fluttercommunity/flutter_launcher_icons#248]
apple@Apples-MBP tools % /bin/sh  /Users/apple/Downloads/codecanyon-QHd5iKbQ-fluxstore-multi-vendor-flutter-ecommerce-full-app/tools/build-icon.sh 
/Users/apple/Downloads/codecanyon-QHd5iKbQ-fluxstore-multi-vendor-flutter-ecommerce-full-app/tools/build-icon.sh: line 2: flutter: command not found
apple@Apples-MBP tools % # Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
zsh: command not found: #

**Comment by EArminjon** [comment]
open your terminal and run "flutter"
The error is explicit : 
```
flutter: command not found
```

**Comment by MarkOSullivan94** [comment]
Looks like a potential issue with your installation of Flutter on your machine
