### ISSUE TITLE
Al agregar flutter web a mi proyecto ya no se muestra el icono, en su lugar muestra una pantalla negra

### ISSUE THREAD

**Issue by ejsp81** [fluttercommunity/flutter_launcher_icons#258]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by RatakondalaArun** [comment]
Closing this as inactive in case this issue still exists please open a new issue
