### ISSUE TITLE
[BUG] The app icon set "AppIcon" has an unassigned child.

### ISSUE THREAD

**Issue by angelocapone** [fluttercommunity/flutter_launcher_icons#259]
Flutter version: 2.2.2
Xcode version: 12.5
flutter_launcher_icons: ^0.9.0

I see the following warning on Xcode under Runner > Runner > Assets.xcassets > AppIcon

`Icon-App-1024x1024@1x.png`
Unassigned
<img width="473" alt="Screen Shot 2021-06-18 at 08 55 44" src="https://user-images.githubusercontent.com/49022955/122520831-69547c80-d014-11eb-8ae4-09f2b9eb0789.png">

**Comment by SmitSonani** [comment]
@angelocapone 
Just replace the name JSON as following.

This error occurs when there is a mismatch in the file name registered under Contents.json and the actual image's filename.

To resolve this,  In the file `ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json`, find out the entry where size is `1024x1024` and replace the filename as `Icon-App-1024x1024@1x.png`.

Following is the complete snippet of that json entry:

`
{
      "size" : "1024x1024",
      "idiom" : "ios-marketing",
      "filename" : "Icon-App-1024x1024@1x.png",
      "scale" : "1x"
    }
`

**Comment by desmeit** [comment]
in my Contents.json there no filename in the list:

```
{
  "images" : [
    {
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "20x20"
    },
    {
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "20x20"
    },
    {
      "idiom" : "iphone",
      "scale" : "1x",
      "size" : "29x29"
    },
    {
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "29x29"
    },
    {
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "29x29"
    },
    {
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "40x40"
    },
    {
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "40x40"
    },
    {
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "60x60"
    },
    {
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "60x60"
    },
    {
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "20x20"
    },
    {
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "20x20"
    },
    {
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "29x29"
    },
    {
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "29x29"
    },
    {
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "40x40"
    },
    {
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "40x40"
    },
    {
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "76x76"
    },
    {
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "76x76"
    },
    {
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "83.5x83.5"
    },
    {
      "idiom" : "ios-marketing",
      "scale" : "1x",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```

**Comment by JackHuang111** [comment]
I had been deleted the whole Contents.json file, and got Asset validation failed every times I trying upload to apple store connect
