### ISSUE TITLE
[BUG] project.pbxproj saves without EOF carriage return

### ISSUE THREAD

**Issue by lukepighetti** [fluttercommunity/flutter_launcher_icons#260]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by kzietek** [comment]
It's related to https://github.com/fluttercommunity/flutter_launcher_icons/issues/43

**Comment by MarkOSullivan94** [comment]
Assuming this should be fixed
