### ISSUE TITLE
Is this package still alive and supported? 

### ISSUE THREAD

**Issue by AlmogRnD** [fluttercommunity/flutter_launcher_icons#266]
Wanted to know if this package is still alive and supported? I see lots of PR's and open issues with decency issues

**Comment by MarkOSullivan94** [comment]
Still alive @AlmogRnD

Been very busy with work in recent times so less time to review and test PRs submitted. I always prefer testing out PRs before merging them in to make sure I don't break Flutter Launcher Icons for everyone using it.

Noticed there was a few PRs for upgrading the `args` dependencies which I merged in and published a new version after slimming down the package as it exceeded the package limit for uploading to [pub.dev](https://pub.dev/)

**Comment by RatakondalaArun** [comment]
Hi, @AlmogRnD we published a roadmap in #379. Closing this as this package is alive.
