### ISSUE TITLE
[BUG] Dependency issue with ^3.0.0-nullsafety.0 and artemis >=6.4.3-beta.1

### ISSUE THREAD

**Issue by AlmogRnD** [fluttercommunity/flutter_launcher_icons#267]
### :information_source: Info
Version:   flutter_launcher_icons: ^0.9.0

### :speech_balloon: Description
Because flutter_launcher_icons >=0.9.0 depends on yaml ^3.0.0-nullsafety.0 and artemis >=6.4.3-beta.1 <7.0.0-beta.2 depends on yaml ^2.2.1, flutter_launcher_icons >=0.9.0 is incompatible with artemis >=6.4.3-beta.1 <7.0.0-beta.2.
So, because ar_drive_app depends on both artemis ^6.17.1 and flutter_launcher_icons ^0.9.0, version solving failed.

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by MarkOSullivan94** [comment]
See: https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/README.md#dependency-incompatible
