### ISSUE TITLE
[BUG] ✗ ERROR: NoConfigFoundException Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section

### ISSUE THREAD

**Issue by M-Shazil** [fluttercommunity/flutter_launcher_icons#270]
I am using this Flutter launcher Icons pkg 
 flutter_launcher_icons: ^0.9.0

Description of problem: I am trying to add the above package in the pubspec.yaml file but it is showing me this error.
I have tried to even add assets too in the flutter but still not working. When I run "flutter pub get" no error is shown.
Then I run the command as mentioned in the readme section of the package ==> 
flutter pub run flutter_launcher_icons:main

Then it fails and shows the following error 
 ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.0)
  ════════════════════════════════════════════

✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section
pub finished with exit code 1

I have shared my complete pubspec.yaml file below: 

### :scroll: Pubspec.yaml
name: travel_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  image_picker: ^0.8.1+3
  path_provider: ^2.0.2
  path: ^1.8.0
  sqflite: ^2.0.0+3
  location: ^4.3.0
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
    flutter_test:
      sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/places.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/icon/places-adaptive.png"

flutter:
  uses-material-design: true

 
Waiting for response anxiously.

**Comment by MarkOSullivan94** [comment]
@M-Shazil it might be to do with your `pubspec.yaml`'s indentation for `flutter_icons` - I can see it's not indented when you pasted in this issue. To be sure you should paste your `pubspec.yaml` into [Gist](https://gist.github.com/) and share it here

**Comment by ghanchi2000** [comment]
when i run command    flutter pub run flutter_launcher_icons:main

i get this error
Could not find package "flutter_launcher_icons". Did you forget to add a dependency?
pub finished with exit code 65

my question is how to generate app icon ?

i noticed flutter_launcher_icons: 0.8.1 removed from pubspec

**Comment by MarkOSullivan94** [comment]
@ghanchi2000 share your pubspec.yaml file, I have found that quite often indentation mistakes can lead to error messages.

**Comment by brunobely** [comment]
Same happening here, I'm using the exact same `flutter_launch_icons.yaml` as in [this example](https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/flavors/flutter_launcher_icons-production.yaml), in the same directory as `pubspec.yaml`. Putting the config inside pubspec solves the issue, but there seems to be a bug using the separate configuration file nonetheless.

**Comment by Nandkishorkumar** [comment]
did you get a fix

**Comment by EssounStephen787845** [comment]
I'm facing same

✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section

**Comment by mnedaa** [comment]
facing this problem

✗ ERROR: NoConfigFoundException
Check that your config file flutter_launcher_icons.yaml has a flutter_icons section

1- uninstall app from phone or emulator

2 - Go To Power Shell and run as Administrator
3 - cd ( your project path )
4- flutter pub get
5 - flutter pub run flutter_launcher_icons:main
6- flutter run

**Comment by RatakondalaArun** [comment]
Closing this as inactive in case this issue still exists please open a new issue

**Comment by muteeabdu11ah** [comment]
It is because of the wrong indentation as I was facing the same problem but now it worked for me
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
 android: true
 ios: true
 image_path: "assets/images/cloudy.png"  

just copy paste it and make your changes hope it will work[](url)
![Capture 1](https://user-images.githubusercontent.com/111283040/185457597-3b08b442-b362-4a86-9a9b-59ce286e28b1.PNG)

**Comment by mcdaqc** [comment]
I just solved the same error you have, and it was something so simple that many of us do not realize it sometimes.

 - Verify that the terminal is in your project folder.
 - Try putting flutter_launcher_icons: any in the dev_dependencies: section like in the image.
 - Verify correct indentation in pubspec.yaml

![Screenshot 2022-08-19 042221](https://user-images.githubusercontent.com/91652245/185588831-cf3bb7c2-f1a1-4f45-8f4c-771606447977.png)
