### ISSUE TITLE
[BUG]  depends on both flutter_svg ^0.22.0 and flutter_launcher_icons ^0.8.0, version solving failed

### ISSUE THREAD

**Issue by gal-Kolberg** [fluttercommunity/flutter_launcher_icons#272]
### :information_source: Info
 "^0.8.0"
Version: `e.g. v0.7.5`

### :speech_balloon: Description

I'm getting this message:
![image](https://user-images.githubusercontent.com/57856944/126128106-c2b4d781-278a-4be5-94ec-917a1fa690bd.png)
and I'm kind of hopeless, I don't know what to do.

[pubspec.txt](https://github.com/fluttercommunity/flutter_launcher_icons/files/6839190/pubspec.txt)

**Comment by VNAPNIC** [comment]
metoo

```
Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and flutter_native_splash 1.2.0 depends on args ^2.1.1, flutter_launcher_icons >=0.9.0 is incompatible with flutter_native_splash 1.2.0.
And because no versions of flutter_native_splash match >1.2.0 <2.0.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_native_splash ^1.2.0.
So, because enstack depends on both flutter_native_splash ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.
pub get failed (1; So, because enstack depends on both flutter_native_splash ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.)
```

**Comment by ertandagdelen** [comment]
> metoo
> 
> ```
> Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and flutter_native_splash 1.2.0 depends on args ^2.1.1, flutter_launcher_icons >=0.9.0 is incompatible with flutter_native_splash 1.2.0.
> And because no versions of flutter_native_splash match >1.2.0 <2.0.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_native_splash ^1.2.0.
> So, because enstack depends on both flutter_native_splash ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.
> pub get failed (1; So, because enstack depends on both flutter_native_splash ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.)
> ```

+1

**Comment by SuperPenguin** [comment]
> ### ℹ️ Info
> "^0.8.0"
> Version: `e.g. v0.7.5`
> 
> ### 💬 Description
> I'm getting this message:
> ![image](https://user-images.githubusercontent.com/57856944/126128106-c2b4d781-278a-4be5-94ec-917a1fa690bd.png)
> and I'm kind of hopeless, I don't know what to do.
> 
> [pubspec.txt](https://github.com/fluttercommunity/flutter_launcher_icons/files/6839190/pubspec.txt)

use version 0.9.0, version 0.8.0 depends on older version of `image`, which depends on older version of `xml`

> metoo
> 
> ```
> Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and flutter_native_splash 1.2.0 depends on args ^2.1.1, flutter_launcher_icons >=0.9.0 is incompatible with flutter_native_splash 1.2.0.
> And because no versions of flutter_native_splash match >1.2.0 <2.0.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_native_splash ^1.2.0.
> So, because enstack depends on both flutter_native_splash ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.
> pub get failed (1; So, because enstack depends on both flutter_native_splash ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.)
> ```

For now you can overrride `args` dependencies so `flutter_launcher_icons` will use `args` 2.1.1, see the workaround here https://github.com/fluttercommunity/flutter_launcher_icons/issues/262

**Comment by ertandagdelen** [comment]
https://github.com/fluttercommunity/flutter_launcher_icons/issues/262#issuecomment-879872076

It worked for me, thanks.

**Comment by MarkOSullivan94** [comment]
@gal-Kolberg does this help - https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/README.md#dependency-incompatible ?

**Comment by gal-Kolberg** [comment]
Yes, Thank you
