### ISSUE TITLE
[BUG] Move package to dev_dependencies

### ISSUE THREAD

**Issue by Techno-Disaster** [fluttercommunity/flutter_launcher_icons#277]
Shouldn't the package be added to dev_dependencies instead of dependencies? The readme looks correct but https://pub.dev/packages/flutter_launcher_icons/install still says dependencies

**Comment by MarkOSullivan94** [comment]
I think that install section is auto generated as I can see json_serializable is the same despite suggesting for it to be installed as `dev_dependency` in the README: https://pub.dev/packages/json_serializable/install
