### ISSUE TITLE
[FEATURE REQUEST] can we lower the sdk: =2.8.0 ?

### ISSUE THREAD

**Issue by mw66** [fluttercommunity/flutter_launcher_icons#288]
Currently,

https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/pubspec.yaml#L14

  sdk: '>=2.12.0-0 <3.0.0'

since this is a `dev_dependencies`, is it possible to lower the sdk to =2.8.0?

Or what is needed from 2.12.0?

Thanks.

**Comment by dvorapa** [comment]
>=2.12.0 is needed for null safety, you should move your projects to null safety too and switch to >=2.12.0 as well. See https://dart.dev/null-safety and https://dart.dev/null-safety/migration-guide

**Comment by RatakondalaArun** [comment]
You can use this as a standalone executable

Install as global package
```shell
flutter pub global activate flutter_launcher_icons:main
```

Run as 
```shell
flutter pub global run flutter_launcher_icons:main
```
Closing this as resolved in case this issue still exists please open a new issue
