### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by skrunexato** [fluttercommunity/flutter_launcher_icons#293]
hi guys installing launcher icon i have this error, how do i fix it?

<img width="741" alt="errorIcon" src="https://user-images.githubusercontent.com/90904312/138073761-fc01ab45-95fa-4e3e-a9a4-04b2b5d747cf.PNG">

**Comment by dvorapa** [comment]
Seems duplicate to #301 and #308

**Comment by bradintheusa** [comment]
This was fixed in 0.9.3
