### ISSUE TITLE
Not overwriting old files?

### ISSUE THREAD

**Issue by ElixirMike** [fluttercommunity/flutter_launcher_icons#296]
I've used the tool to successfully generate the icons. I am now changing the icon to something different (new name and I update the pubspec.yaml file with new name). I run the command line tool which says it ran successfully, but when I run the app, the old icons are still there?

After generating the icon, I look in the /android/app/src/main/res subfolders...and the old icon appears there.
Is this a bug? do I need to manually delete these files before rerunning the command line?

**Comment by ankitkarna99** [comment]
Hi @ElixirMike, Can you elaborate how you did this? I have run into the same issue.
