### ISSUE TITLE
[BUG] Unhandled exception

### ISSUE THREAD

**Issue by leech001** [fluttercommunity/flutter_launcher_icons#301]
### :information_source: Info
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.6.0-12.0.pre.779, on Microsoft Windows [Version 10.0.19042.1348], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code, 64-bit edition (version 1.62.3)
[√] Connected device (4 available)

### :speech_balloon: Description
 flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.1)
  ════════════════════════════════════════════

✓ Successfully generated launcher icons
Unhandled exception:
FormatException: Invalid number (at character 1)

^
#0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
#1      int.parse (dart:core-patch/integers_patch.dart:55:14)
#2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
#3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
#4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#5      main (file:///C:/Users/Tom/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
pub finished with exit code 255

### :scroll: Pubspec.yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/moto.png"

**Comment by ltdangkhoa** [comment]
I think this bug happend in master branch with Android. When I tried to block the ```android: "launcher_icon"```, the script worked and still generate icons of iOS version. 

Looking for the fix from maintaining team.

**Comment by lrorpilla** [comment]
A solution to this is to go into your app-level `build.gradle` and change your `minSdkVersion` to a number (`16` worked for me), then change it back once you've generated the icons.

But yeah, it should really be able to adapt and work with `flutter.minSdkVersion`.

**Comment by dvorapa** [comment]
Seems duplicate to #293 and #308

**Comment by leech001** [comment]
Solution found
#https://github.com/fluttercommunity/flutter_launcher_icons/compare/master...marcobazzani:patch-1
