### ISSUE TITLE
[BUG] Launcher Icon not changing on device Xiaomi Mi MIX 2 (Android)

### ISSUE THREAD

**Issue by sentd94** [fluttercommunity/flutter_launcher_icons#303]
Been using the latest version. Icon has been successfully changed on other Android devices. Maybe it's worth mentioning this device is using squared icons (not rounded).

From my **pubspec.yaml**:

> flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path_ios: "assets/icon/money-icon.png"
    image_path_android: "assets/icon/money-icon.png"
    image_path: "assets/icon/money-icon.png"

 
I noticed that in the android mipmap folders there are 2 images. The default flutter icon (ic_launcher) and the new one (launcher_icon).
Android seems to be using the default flutter icon.

[https://imgur.com/a/d7UwlUa](https://imgur.com/a/d7UwlUa)

**Comment by RatakondalaArun** [comment]
Closing this as inactive in case this issue still exists please open a new issue
