### ISSUE TITLE
[BUG] Flutter 2.8.0 incompatibility

### ISSUE THREAD

**Issue by Flanker72** [fluttercommunity/flutter_launcher_icons#308]
### :information_source: Info

Version: `v0.9.2`

### :speech_balloon: Description

Problem appears after upgrading to latest stable Flutter (2.8.0):

```
$ flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.1)                               
  ════════════════════════════════════════════
  

✓ Successfully generated launcher icons
Unhandled exception:
FormatException: Invalid number (at character 1)

^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
#1      int.parse (dart:core-patch/integers_patch.dart:55:14)
#2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
#3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
#4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#5      main (file:///usr/local/Caskroom/flutter/1.22.5/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

`flutter doctor` output:
```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)
    ! Error: Flanker iPhone is not connected. Xcode will continue when Flanker iPhone is connected. (code -13)

• No issues found!
```

Since 2.8.0 Flutter upgraded build.gradle and included variables for versions. flutter_launcher_icons wants to get number instead.

See [this comment](https://github.com/fluttercommunity/flutter_launcher_icons/issues/88#issuecomment-990137402) for more information.

**Comment by sunderee** [comment]
Same issue here. I thought that maybe the problem could be solved by updating the `local.properties` file by explicitly declaring the minimum SDK version, but it didn't work. So I hope something can be done here soon...

**Comment by zbahadir** [comment]
I have the same problem.
I tried the suggestions in the other thread. I couldn't solve the problem.

**Comment by Roaa94** [comment]
Having the same problem here.

**Comment by Roaa94** [comment]
> ### ℹ️ Info
> Version: `v0.9.2`
> 
> ### 💬 Description
> Problem appears after upgrading to latest stable Flutter (2.8.0):
> 
> ```
> $ flutter pub run flutter_launcher_icons:main
>   ════════════════════════════════════════════
>      FLUTTER LAUNCHER ICONS (v0.9.1)                               
>   ════════════════════════════════════════════
>   
> 
> ✓ Successfully generated launcher icons
> Unhandled exception:
> FormatException: Invalid number (at character 1)
> 
> ^
> 
> #0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
> #1      int.parse (dart:core-patch/integers_patch.dart:55:14)
> #2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
> #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
> #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
> #5      main (file:///usr/local/Caskroom/flutter/1.22.5/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
> #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
> #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> pub finished with exit code 255
> ```
> 
> `flutter doctor` output:
> 
> ```
> % flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-RU)
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] VS Code (version 1.62.3)
> [✓] Connected device (2 available)
>     ! Error: Flanker iPhone is not connected. Xcode will continue when Flanker iPhone is connected. (code -13)
> 
> • No issues found!
> ```
> 
> Since 2.8.0 Flutter upgraded build.gradle and included variables for versions. flutter_launcher_icons wants to get number instead.
> 
> See [this comment](https://github.com/fluttercommunity/flutter_launcher_icons/issues/88#issuecomment-990137402) for more information.

Changing the following in the app/build.gradle file fixed it for me
![image](https://user-images.githubusercontent.com/50345358/145870530-4df813d0-67ab-422c-bb9d-984819d4de3e.png)

**Comment by sunderee** [comment]
So we're supposed to temporarily hardcode versions, and then revert back to using Gradle variables? I mean, it's a fix, but I wonder if there's a way not to go through this step or maybe update documentation?

**Comment by Roaa94** [comment]
> So we're supposed to temporarily hardcode versions, and then revert back to using Gradle variables? I mean, it's a fix, but I wonder if there's a way not to go through this step or maybe update documentation?

I'm not sure I understand you right, but my suggestion was just a quick fix option, you can hard code it or add it to a file or whatever works. The point is to assign a value to those variables so that they can be read. But you're right the documentation should be updated I guess

**Comment by PratikMMohite** [comment]
Looks like from now on needed minSdkVersion, targetSdkVersion read from "{SDK_PATH}\packages\flutter_tools\gradle\flutter.gradle" file

**Comment by teerasej** [comment]
> > ### ℹ️ Info
> > Version: `v0.9.2`
> > ### 💬 Description
> > Problem appears after upgrading to latest stable Flutter (2.8.0):
> > ```
> > $ flutter pub run flutter_launcher_icons:main
> >   ════════════════════════════════════════════
> >      FLUTTER LAUNCHER ICONS (v0.9.1)                               
> >   ════════════════════════════════════════════
> >   
> > 
> > ✓ Successfully generated launcher icons
> > Unhandled exception:
> > FormatException: Invalid number (at character 1)
> > 
> > ^
> > 
> > #0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
> > #1      int.parse (dart:core-patch/integers_patch.dart:55:14)
> > #2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
> > #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
> > #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
> > #5      main (file:///usr/local/Caskroom/flutter/1.22.5/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
> > #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
> > #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> > pub finished with exit code 255
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `flutter doctor` output:
> > ```
> > % flutter doctor
> > Doctor summary (to see all details, run flutter doctor -v):
> > [✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-RU)
> > [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
> > [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> > [✓] Chrome - develop for the web
> > [✓] Android Studio (version 2020.3)
> > [✓] VS Code (version 1.62.3)
> > [✓] Connected device (2 available)
> >     ! Error: Flanker iPhone is not connected. Xcode will continue when Flanker iPhone is connected. (code -13)
> > 
> > • No issues found!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since 2.8.0 Flutter upgraded build.gradle and included variables for versions. flutter_launcher_icons wants to get number instead.
> > See [this comment](https://github.com/fluttercommunity/flutter_launcher_icons/issues/88#issuecomment-990137402) for more information.
> 
> ### Changing the following in the app/src/build.gradle file fixed it for me
> ![image](https://user-images.githubusercontent.com/50345358/145872853-75285529-722a-4666-af32-253e11cf8717.png)
> 
> ### Or simply add numbers for minSdkVersion & targetSdkVersion
> ![image](https://user-images.githubusercontent.com/50345358/145870530-4df813d0-67ab-422c-bb9d-984819d4de3e.png)

apply specific version in defaultConfig fixed the error for me

**Comment by hayatbangash55** [comment]
same issue..

**Comment by arhamcode** [comment]
Same issue here, I hope something can be done here soon...

**Comment by LUK3D** [comment]
Same here...

**Comment by Roaa94** [comment]
@hayatbangash55 & @arhamcode & @LUK3D 

> > ### ℹ️ Info
> > Version: `v0.9.2`
> > ### 💬 Description
> > Problem appears after upgrading to latest stable Flutter (2.8.0):
> > ```
> > $ flutter pub run flutter_launcher_icons:main
> >   ════════════════════════════════════════════
> >      FLUTTER LAUNCHER ICONS (v0.9.1)                               
> >   ════════════════════════════════════════════
> >   
> > 
> > ✓ Successfully generated launcher icons
> > Unhandled exception:
> > FormatException: Invalid number (at character 1)
> > 
> > ^
> > 
> > #0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
> > #1      int.parse (dart:core-patch/integers_patch.dart:55:14)
> > #2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
> > #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
> > #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
> > #5      main (file:///usr/local/Caskroom/flutter/1.22.5/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
> > #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
> > #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> > pub finished with exit code 255
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `flutter doctor` output:
> > ```
> > % flutter doctor
> > Doctor summary (to see all details, run flutter doctor -v):
> > [✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-RU)
> > [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
> > [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> > [✓] Chrome - develop for the web
> > [✓] Android Studio (version 2020.3)
> > [✓] VS Code (version 1.62.3)
> > [✓] Connected device (2 available)
> >     ! Error: Flanker iPhone is not connected. Xcode will continue when Flanker iPhone is connected. (code -13)
> > 
> > • No issues found!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since 2.8.0 Flutter upgraded build.gradle and included variables for versions. flutter_launcher_icons wants to get number instead.
> > See [this comment](https://github.com/fluttercommunity/flutter_launcher_icons/issues/88#issuecomment-990137402) for more information.
> 
> ### Changing the following in the app/src/build.gradle file fixed it for me
> ![image](https://user-images.githubusercontent.com/50345358/145872853-75285529-722a-4666-af32-253e11cf8717.png)
> 
> ### Or simply add numbers for minSdkVersion & targetSdkVersion
> ![image](https://user-images.githubusercontent.com/50345358/145870530-4df813d0-67ab-422c-bb9d-984819d4de3e.png)

Didn't this solve the issue for you? @hayatbangash55 & @arhamcode & @LUK3D

**Comment by hayatbangash55** [comment]
> @hayatbangash55 & @arhamcode & @LUK3D
> 
> > > ### ℹ️ Info
> > > Version: `v0.9.2`
> > > ### 💬 Description
> > > Problem appears after upgrading to latest stable Flutter (2.8.0):
> > > ```
> > > $ flutter pub run flutter_launcher_icons:main
> > >   ════════════════════════════════════════════
> > >      FLUTTER LAUNCHER ICONS (v0.9.1)                               
> > >   ════════════════════════════════════════════
> > >   
> > > 
> > > ✓ Successfully generated launcher icons
> > > Unhandled exception:
> > > FormatException: Invalid number (at character 1)
> > > 
> > > ^
> > > 
> > > #0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
> > > #1      int.parse (dart:core-patch/integers_patch.dart:55:14)
> > > #2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
> > > #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
> > > #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
> > > #5      main (file:///usr/local/Caskroom/flutter/1.22.5/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
> > > #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
> > > #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> > > pub finished with exit code 255
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `flutter doctor` output:
> > > ```
> > > % flutter doctor
> > > Doctor summary (to see all details, run flutter doctor -v):
> > > [✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-RU)
> > > [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
> > > [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> > > [✓] Chrome - develop for the web
> > > [✓] Android Studio (version 2020.3)
> > > [✓] VS Code (version 1.62.3)
> > > [✓] Connected device (2 available)
> > >     ! Error: Flanker iPhone is not connected. Xcode will continue when Flanker iPhone is connected. (code -13)
> > > 
> > > • No issues found!
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Since 2.8.0 Flutter upgraded build.gradle and included variables for versions. flutter_launcher_icons wants to get number instead.
> > > See [this comment](https://github.com/fluttercommunity/flutter_launcher_icons/issues/88#issuecomment-990137402) for more information.
> > 
> > 
> > ### Changing the following in the app/src/build.gradle file fixed it for me
> > ![image](https://user-images.githubusercontent.com/50345358/145872853-75285529-722a-4666-af32-253e11cf8717.png)
> > ### Or simply add numbers for minSdkVersion & targetSdkVersion
> > ![image](https://user-images.githubusercontent.com/50345358/145870530-4df813d0-67ab-422c-bb9d-984819d4de3e.png)
> 
> Didn't this solve the issue for you? @hayatbangash55 & @arhamcode & @LUK3D

no

**Comment by ceedadev** [comment]
same issue here

**Comment by marcobazzani** [comment]
this PR should fix it https://github.com/fluttercommunity/flutter_launcher_icons/compare/master...marcobazzani:patch-1

**Comment by dvorapa** [comment]
Seems duplicate to #293 and #301

**Comment by zbahadir** [comment]
> this PR should fix it [master...marcobazzani:patch-1](https://github.com/fluttercommunity/flutter_launcher_icons/compare/master...marcobazzani:patch-1)

Thank you so much. It was very helpful.

**Comment by dhruvinprajapati** [comment]
> > ### ℹ️ Info
> > Version: `v0.9.2`
> > ### 💬 Description
> > Problem appears after upgrading to latest stable Flutter (2.8.0):
> > ```
> > $ flutter pub run flutter_launcher_icons:main
> >   ════════════════════════════════════════════
> >      FLUTTER LAUNCHER ICONS (v0.9.1)                               
> >   ════════════════════════════════════════════
> >   
> > 
> > ✓ Successfully generated launcher icons
> > Unhandled exception:
> > FormatException: Invalid number (at character 1)
> > 
> > ^
> > 
> > #0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
> > #1      int.parse (dart:core-patch/integers_patch.dart:55:14)
> > #2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
> > #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
> > #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
> > #5      main (file:///usr/local/Caskroom/flutter/1.22.5/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
> > #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
> > #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> > pub finished with exit code 255
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `flutter doctor` output:
> > ```
> > % flutter doctor
> > Doctor summary (to see all details, run flutter doctor -v):
> > [✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-RU)
> > [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
> > [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> > [✓] Chrome - develop for the web
> > [✓] Android Studio (version 2020.3)
> > [✓] VS Code (version 1.62.3)
> > [✓] Connected device (2 available)
> >     ! Error: Flanker iPhone is not connected. Xcode will continue when Flanker iPhone is connected. (code -13)
> > 
> > • No issues found!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since 2.8.0 Flutter upgraded build.gradle and included variables for versions. flutter_launcher_icons wants to get number instead.
> > See [this comment](https://github.com/fluttercommunity/flutter_launcher_icons/issues/88#issuecomment-990137402) for more information.
> 
> ### Changing the following in the app/src/build.gradle file fixed it for me
> ![image](https://user-images.githubusercontent.com/50345358/145872853-75285529-722a-4666-af32-253e11cf8717.png)
> 
> ### Or simply add numbers for minSdkVersion & targetSdkVersion
> ![image](https://user-images.githubusercontent.com/50345358/145870530-4df813d0-67ab-422c-bb9d-984819d4de3e.png)

that solve my problem, but when should it update on main package

**Comment by gkysrt** [comment]
Problem occurs when you have multiple string lines that contain "minSdkVersion" in build.gradle.
In my experience, this segment of build.gradle caused the error. 
![image](https://user-images.githubusercontent.com/34637265/148015613-67235ae2-0fbb-41be-a5e3-6fb21f69212d.png)

In the source code, a loop that iterates every line hits the first line of this segment. Eventually, trying to parse an empty string to integer, it fails. 

![image](https://user-images.githubusercontent.com/34637265/148015965-655d20e0-9cd5-4adc-b442-4162273e0288.png)

To fix this, I simply added a empty string check condition on line 309, before int.parse()

Hope it proves helpful

**Comment by ProgrammingLife** [comment]
Tried all of the solutions here but nothing worked for me.

**Comment by DouglasCarterBor** [comment]
> esse PR deve corrigir [mestre...marcobazzani:patch-1](https://github.com/fluttercommunity/flutter_launcher_icons/compare/master...marcobazzani:patch-1)


It worked for me, thank you very much!
