### ISSUE TITLE
Control zoom for icons [FEATURE REQUEST]

### ISSUE THREAD

**Issue by khari998** [fluttercommunity/flutter_launcher_icons#309]
My icon developed for android needs to cover the entire circle. Right now it is contained within the circle and does not look right. The only solution I've found is to try and use the Image asset tool in Android Studio to control the zoom but that is broken for me. I would recommend adding it as a property on the pubspec.yaml. Would love to just state 2.0 as a value and my icon would be zoomed in at 2x and would fill the circle.

**Comment by MarkOSullivan94** [comment]
This might solve your issue: https://github.com/fluttercommunity/flutter_launcher_icons/pull/563
