### ISSUE TITLE
[FEATURE REQUEST] desktop icon support (Windows and Winuwp, Linux, MacOS)

### ISSUE THREAD

**Issue by Areopagitics** [fluttercommunity/flutter_launcher_icons#314]
please add support for desktop icons

thank you!

**Comment by andreclinio** [comment]
Agree!

**Comment by Areopagitics** [comment]
it looks like there might be some support already:

https://github.com/fluttercommunity/flutter_launcher_icons/pull/189

**Comment by RatakondalaArun** [comment]
This is being tracked in #379
