### ISSUE TITLE
[BUG] flutter_launcher_icons Exception

### ISSUE THREAD

**Issue by bahiraei** [fluttercommunity/flutter_launcher_icons#315]
### :information_source: Info
Version: `v0.9.2`

### :speech_balloon: Description

flutter_launcher_icons Exception

` ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.1)
  ════════════════════════════════════════════

✓ Successfully generated launcher icons
Unhandled exception:
FormatException: Invalid number (at character 1)

^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
#1      int.parse (dart:core-patch/integers_patch.dart:55:14)
#2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
#3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
#4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#5      main (file:///C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

`

### :scroll: Pubspec.yaml
[https://file.io/t2cnTZ7bRxRb](url)

**Comment by Shibrain** [comment]
Did you find a solution for this?
