### ISSUE TITLE
Flutter icon

### ISSUE THREAD

**Issue by supakitwong** [fluttercommunity/flutter_launcher_icons#320]
Hi
I got "pub finished with exit code 255" from running flutter pub run flutter_launcher_icons:main.
How i fix it?

Thanks

**Comment by andresgutice** [comment]
I have the same issue

**Comment by Adaptabledesigner** [comment]
C:\Users\vasanth\Desktop\PATTRAI\my_application>flutter pub get
Running "flutter pub get" in my_application...                   1,723ms

C:\Users\vasanth\Desktop\PATTRAI\my_application>flutter pub run flutter_launcher_icons:main -f <your config file name here>
The syntax of the command is incorrect.

**Comment by RatakondalaArun** [comment]
Closing this as inactive
