### ISSUE TITLE
[BUG] Unhandled exception: FormatException: Invalid number (at character 1)

### ISSUE THREAD

**Issue by codewithmalik** [fluttercommunity/flutter_launcher_icons#333]
### :information_source: Info

Version: `e.g. v0.9.2`

### :speech_balloon: Description

I updated flutter to 2.10.0, I ran the command and it showed successfully " Successfully generated launcher icons" but below the successful sentence I got this below message

Unhandled exception:
FormatException: Invalid number (at character 1)

^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
#1      int.parse (dart:core-patch/integers_patch.dart:55:14)
#2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
#3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
#4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#5      main (file:///Users/aoomle/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

**Comment by kanggara75** [comment]
![Screen Shot 2022-02-05 at 14 30 05](https://user-images.githubusercontent.com/24321218/152633029-c134c377-73f6-4d1b-ab9c-d0d9ec52bca5.png)

i have same bug like yours, with v0.9.1

**Comment by wocodes** [comment]
Experienced same here

**Comment by kanggara75** [comment]
> ### ℹ️ Info
> Version: `e.g. v0.9.2`
> 
> ### 💬 Description
> I updated flutter to 2.10.0, I ran the command and it showed successfully " Successfully generated launcher icons" but below the successful sentence I got this below message
> 
> Unhandled exception: FormatException: Invalid number (at character 1)
> 
> ^
> 
> #0 int._handleFormatError (dart:core-patch/integers_patch.dart:129:7) #1 int.parse (dart:core-patch/integers_patch.dart:55:14) #2 minSdk (package:flutter_launcher_icons/android.dart:309:18) #3 createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47) #4 createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7) #5 main (file:///Users/aoomle/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26) #6 _delayEntrypointInvocation. (dart:isolate-patch/isolate_patch.dart:295:32) #7 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12) pub finished with exit code 255

change file android/app/build.gradle
from this
![Screen Shot 2022-02-05 at 15 13 29](https://user-images.githubusercontent.com/24321218/152634178-a57344d4-6f52-4b06-bbb9-ebf4ad7229fe.png)
 to this 
![Screen Shot 2022-02-05 at 15 14 08](https://user-images.githubusercontent.com/24321218/152634196-f3347cdb-eb3f-4fb0-b95c-3e8d545433d1.png)

**Comment by kagouda** [comment]
I just got the same error and fixed it by manually setting the `minSdkVersion` in `android/app/build.gradle`

```
    defaultConfig {
        applicationId "com.example.foo"
        minSdkVersion 16 // <<== set this
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```

New Flutter projects now have the `minSdkVersion` set to `flutter.minSdkVersion` which (currently) resolves to 16 but it appears the package does not pick up that value.

EDIT: Note, `minSDKVersion 16` is the bare minimum. Some apps may require a higher minimum for like 19 or even 21 depending on what plugins you have installed (e.g. WebView, Google Maps and several FlutterFire plugins etc.)

_Originally posted by @cklanac in https://github.com/fluttercommunity/flutter_launcher_icons/issues/324#issuecomment-1005851670_

**Comment by harlekintiger** [comment]
Also important: You can't have the string 'minSdkVersion' anywhere before the actual declaration of the min SDK Version! If you did `//minSdkVersion flutter.minSdkVersion` above the version it will crash. Remove it or move it down below the actual declaration.
Maybe the plugin should check if a line is commented out and ignore those

**Comment by MikulasVanousek** [comment]
I have the same issue. I think solving it by removing flutter.minSdkVersion goes against having things specified in pubspce.yaml, which is the reason I wanted to use this package in the first place.

**Comment by Clashkid155** [comment]
It showing  `✓ Successfully generated launcher icons` gives the impression that it actually succeed. I think that should be fixed too.

**Comment by MikiVanousek** [comment]
It is actually the same fir other people's production flutter apps on my device ![Screenshot_20220330-150510_Yoga.png](https://user-images.githubusercontent.com/33402194/160841583-73dfaeed-72e8-456b-95e6-a771765d56ea.png)

**Comment by abrarali-official** [comment]
I also facing this error. Can anyone tell me the solution?

**Comment by MikiVanousek** [comment]
It is not solved.
