### ISSUE TITLE
macOS icon support?

### ISSUE THREAD

**Issue by lucasjinreal** [fluttercommunity/flutter_launcher_icons#334]
macOS icon support?

**Comment by andreclinio** [comment]
hope to see it soon!

**Comment by deimantasa** [comment]
Any updates on this?

**Comment by hhstore** [comment]
## Issues related:

#255 
#334 
#140 
#189 


## PRs related: 

- https://github.com/fluttercommunity/flutter_launcher_icons/pull/255
- https://github.com/fluttercommunity/flutter_launcher_icons/pull/189

**Comment by scysys** [comment]
Im also here because of MacOS. Im found a fork to this great project which supports it: https://pub.dev/packages/icons_launcher

**Comment by nohli** [comment]
Support for macOS icons came in [September '22](https://pub.dev/packages/flutter_launcher_icons/changelog#0110-27th-september-2022).
Can this issue be closed?
