### ISSUE TITLE
[BUG] iOS settings flutter default icon

### ISSUE THREAD

**Issue by fedecarroz** [fluttercommunity/flutter_launcher_icons#335]
flutter_launcher_icons version: 0.9.2
OS: iOS

Problem:
In iOS settings there is the flutter default icon even if the app icon has been updated in the app menu.

![image](https://user-images.githubusercontent.com/73960020/153099817-8fa6e498-6310-4493-a27e-6a94dec50be3.png)

[PUBSPEC.YAML]
...
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
...

**Comment by RatakondalaArun** [comment]
Hi @fedecarroz 
You should be able to solve this by restarting your device

closing this issue. In case it occurs again please reopen
