### ISSUE TITLE
flutter_launcher_icons

### ISSUE THREAD

**Issue by Sayedoon99** [fluttercommunity/flutter_launcher_icons#344]
Hello...
I made the icon for my app in the flutter but I can't see the icon, How can I solve the problem
![Screenshot 2022-03-03 191638](https://user-images.githubusercontent.com/99115972/156606877-85f93668-5cdd-4303-abfd-2cc27b244fd2.png)

**Comment by devj3ns** [comment]
@Sayedoon99 @KurtLa 

Have a look at this issue: https://github.com/fluttercommunity/flutter_launcher_icons/issues/333

**Comment by KurtLa** [comment]
> @Sayedoon99 @KurtLa
> 
> Have a look at this issue: #333

Ah yeah, thanks a Lot!
