### ISSUE TITLE
not found for signing config 'release'

### ISSUE THREAD

**Issue by Sayedoon99** [fluttercommunity/flutter_launcher_icons#346]
I have problem I did all step to create keystores and how can I fix this error
![issue error](https://user-images.githubusercontent.com/99115972/157636718-8c45aaed-dd5f-4ac9-8fef-564736996506.png)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:signReleaseBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Failed to read key keystore01 from store "c:\Users\saydo\AndroidKeys\keystore01.jks": No key with alias 'keystore01' found in keystore c:\Users\saydo\AndroidKeys\keystore01.jks

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'bundleRelease'...                             12.6s
Gradle task bundleRelease failed with exit code 1

I need to fix this error please.....

**Comment by bradintheusa** [comment]
Hi,

This is not related to flutter_launcher_icons, 

This link will explain what you need  [Build and release an Android app](https://docs.flutter.dev/deployment/android)
