### ISSUE TITLE
[Question] Anyone know how to add linux icon, please help.

### ISSUE THREAD

**Issue by gsmlg** [fluttercommunity/flutter_launcher_icons#347]
Anyone know how to add Linux app icon, please help.

**Comment by itsahmed-dev** [comment]
> Anyone know how to add Linux app icon, please help.

Anyone?

**Comment by gsmlg** [comment]
> > Anyone know how to add Linux app icon, please help.
> 
> 
> 
> Anyone?

Someone had done. 👼

**Comment by itsahmed-dev** [comment]
How?

**Comment by gsmlg** [comment]
Flutter generated linux application does not support app icon.
