### ISSUE TITLE
Add web support

### ISSUE THREAD

**Issue by prggTheProgrammer** [fluttercommunity/flutter_launcher_icons#348]
### :speech_balloon: Description
It would be nice if this plugin was also available for web. Something that automated [this](https://stackoverflow.com/a/56746084/17581223) process.

### :question: Platform
This is specific for web

**Comment by bradintheusa** [comment]
That's a lot of icons. I normally just make one.

**Comment by RatakondalaArun** [comment]
As a initial web support we can add default flutter icon sizes that are included in bootstrap code

This are the default web fav icons generated by flutter when we create a new project
![image](https://user-images.githubusercontent.com/47482264/175608956-340aa46e-de09-4349-a40a-2257826d19b1.png)

manifest.json
```json
{
    "name": "demo",
    "short_name": "demo",
    "start_url": ".",
    "display": "standalone",
    "background_color": "#0175C2",
    "theme_color": "#0175C2",
    "description": "A new Flutter project.",
    "orientation": "portrait-primary",
    "prefer_related_applications": false,
    "icons": [
        {
            "src": "icons/Icon-192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "icons/Icon-512.png",
            "sizes": "512x512",
            "type": "image/png"
        },
        {
            "src": "icons/Icon-maskable-192.png",
            "sizes": "192x192",
            "type": "image/png",
            "purpose": "maskable"
        },
        {
            "src": "icons/Icon-maskable-512.png",
            "sizes": "512x512",
            "type": "image/png",
            "purpose": "maskable"
        }
    ]
}

```

As an initial support for web we can generate icons for web with this sizes. `192`, `512`
cc @MarkOSullivan94
