### ISSUE TITLE
Android Studio : pub finished with exit code 255

### ISSUE THREAD

**Issue by ashishazilen** [fluttercommunity/flutter_launcher_icons#352]
### :information_source: Info

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

### :speech_balloon: Description

#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

### :scroll: Pubspec.yaml

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"

**Comment by alexandranb1** [comment]
Hello,

I have the same issue, did you manage to find a solution?

Thank you

**Comment by MohammedAlabadla** [comment]
I have the same issue

**Comment by williamluke4** [comment]
I did some digging and it seems that this is related to this bit of the code https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/lib/android.dart#L309 basically `int.parse(minSdk)` is called with an empty string. 
I assume this happens when your `build.gradle` file contains the following instead of a static value for the minVersion.
```
  defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.grassecon.org.my_sarafu"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```
As a quick hack you can change the following line https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/lib/android.dart#L309
```diff
- return int.parse(minSdk);
+ return minSdk.isNotEmpty ? int.parse(minSdk) : 0;
```

**Comment by yinrong** [comment]
@williamluke4 not working.

in my situation, it works after `flutter clean`

**Comment by ranfen** [comment]
> I did some digging and it seems that this is related to this bit of the code https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/lib/android.dart#L309 basically `int.parse(minSdk)` is called with an empty string. I assume this happens when your `build.gradle` file contains the following instead of a static value for the minVersion.
> 
> ```
>   defaultConfig {
>         applicationId "com.grassecon.org.my_sarafu"
>         minSdkVersion flutter.minSdkVersion
>         targetSdkVersion flutter.targetSdkVersion
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>     }
> ```
> 
> As a quick hack you can change the following line https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/lib/android.dart#L309
> 
> ```diff
> - return int.parse(minSdk);
> + return minSdk.isNotEmpty ? int.parse(minSdk) : 0;
> ```

This solved the problem thanks

**Comment by essenJean223** [comment]
Other solution that you can try is edit the `build.gradle` file which is in the `android/app` folder.
In the section: `defaultConfig{...}` you need to specify the `minSdkVersion`.  In my case I put the 22 version.
It would seems like this:
```
defaultConfig {
        applicationId "com.pruebajp.prueba"
        minSdkVersion 22 //THIS LINE
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```
I hope this helps.

**Comment by riswanmsm** [comment]
edit the file android/app/build.gradle and chnage the params like below 

 minSdkVersion 21
 targetSdkVersion 29

after the change run the below commands in terminal

 flutter pub get
 flutter pub run flutter_launcher_icons:main

after generating the icons change back the edited above line to original

**Comment by LahaLuhem** [comment]
I have an easy fix:

1. Change Line 308 in Dart Packages/flutter_launcher_icons/android.dart:
   + previous: `final String minSdk = line.replaceAll(RegExp(r'[^\d]'), '');`
   + change to: `final String minSdk = "21"`
2. Recompile the packages by running `flutter clean`, followed by `flutter pub get` again
3. Run generating procedure again by `flutter pub run flutter_launcher_icons:main`

It just skips the parsing of the manifest file directly to get the minSDK version line.

**Comment by darkrisen3** [comment]
> edit the file android/app/build.gradle and chnage the params like below
> 
> ```
>  minSdkVersion 21
>  targetSdkVersion 29
> ```
> 
> after the change run the below commands in terminal
> 
> ```
>  flutter pub get
>  flutter pub run flutter_launcher_icons:main
> ```
> 
> after generating the icons successfully, change back the edited above lines like to their original form like below
> 
> ```
> minSdkVersion flutter.minSdkVersion
> targetSdkVersion flutter.targetSdkVersion
> ```

this worked for me, but I did not change back the syntax as you showed in the last step, will that be a problem?
