### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by TariqHattab** [fluttercommunity/flutter_launcher_icons#358]
Can I use this package to change the icons at run time after I created and launched the app??

**Comment by NishchayShakya1** [comment]
> Can I use this package to change the icons at run time after I created and launched the app??

Yes, You can change the icon at run time, if your app is in debug mode.

**Comment by RatakondalaArun** [comment]
Hi @TariqHattab you cannot use this package to set dynamic icons

It must be done through native code. Please refer to the below links from **Stackoverflow**
- `android`: https://stackoverflow.com/questions/1103027/how-to-change-an-application-icon-programmatically-in-android
- `IOS`: https://stackoverflow.com/questions/70294916/is-there-any-way-to-change-the-icon-of-my-app-dynamically-in-ios

What this package does is create static icons for given platforms and add it to there respective directories
