### ISSUE TITLE
Project Discontinued?

### ISSUE THREAD

**Issue by Miamoto-Musashi** [fluttercommunity/flutter_launcher_icons#361]
Is the project abandoned?
don't see a commit from August and many issue arise

thx

**Comment by normidar** [comment]
it seems like.....
have some one create a better fork?

**Comment by sbritorodr** [comment]
> it seems like.....
> have someone created a better fork?

Yes! I'm using this and works pretty good:
https://pub.dev/packages/icons_launcher

Also this:
https://pub.dev/packages/flutter_launcher_icons_maker

**Comment by bradintheusa** [comment]
A new release was just issued today.  We are going through the issues and pull requests now.
