### ISSUE TITLE
Automate the publishing of new versions with GitHub Actions CD pipeline 

### ISSUE THREAD

**Issue by MarkOSullivan94** [fluttercommunity/flutter_launcher_icons#369]
### :speech_balloon: Description

As pointed out by @RatakondalaArun there's no CD pipeline in place to automate the publication of new versions of this package: https://github.com/fluttercommunity/flutter_launcher_icons/issues/363#issuecomment-1148201456

Right now, I am essentially a bottleneck and could slow down / delay new versions from being published if I'm unavailable and so it would be great that any new tag starting with `v` would result in a new version of the package being published to pub.

Resource: https://www.bradcypert.com/dart-packages-with-github-actions/

**Comment by RatakondalaArun** [comment]
I think it will be better if we could trigger the CD workflow when we publish a package new release on GitHub instead of tag push

```yaml
name: CD

on:
  release:
    types: [published]

```
cc @bradintheusa

**Comment by MarkOSullivan94** [comment]
@RatakondalaArun definitely would much rather that!

**Comment by bradintheusa** [comment]
I like the new release Idea. That's how I set my projects up and it works well.

**Comment by RatakondalaArun** [comment]
@MarkOSullivan94 we also need a CI pipeline for PRs and tests

I can work on the CI pipeline as a separate PR if you are occupied.

as a bonus we can have a code-coverage as well 🙂 `flutter test all_tests.dart --coverage`

**Comment by MarkOSullivan94** [comment]
@RatakondalaArun what CI pipeline are you planning to do?

Migrating the existing one from Travis to GitHub actions?

**Comment by RatakondalaArun** [comment]
I didn't notice that there is a Travis CI in place.

I think it's better if we can migrate the CI pipeline to GitHub as well because it can provide better visibility for PR reviews
