### ISSUE TITLE
What resolution should the provided icon be?

### ISSUE THREAD

**Issue by timmiller17** [fluttercommunity/flutter_launcher_icons#37]
I'm coming from an Android background.  What resolution should I provide to this library?  Similar to xhdpi perhaps?

**Comment by franzsilva** [comment]
hi @timmiller17, the best way is to provide a large square image probably 1024x1024, the tool will scale down to all the necessary resolutions.

**Comment by MarkOSullivan94** [comment]
@timmiller17 I've tried with multiple resolutions (as you can see from the [example project](https://github.com/fluttercommunity/flutter_launcher_icons/tree/master/example)) all of these work but I haven't yet done enough testing to provide a recommended resolution.
