### ISSUE TITLE
ERROR: Cannot find minSdk

### ISSUE THREAD

**Issue by JordanTYC** [fluttercommunity/flutter_launcher_icons#371]
Version: 0.9.3

✗ ERROR: InvalidConfigException
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties

**Comment by git-akihakune** [comment]
Or, to be a little more specific:

### :information_source: Info
Version: `0.9.3`
Flutter version: `3.0.4` (stable)
Dart version: `2.17.5`

### :speech_balloon: Description


Running `flutter pub run flutter_launcher_icons:main` triggered an error:
```
 ERROR: InvalidConfigException 
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties
#0      createIconsFromConfig (package:flutter_launcher_icons/main.dart:96:7)
#1      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#2      main (file:///home/user/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.3/bin/main.dart:7:26)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

App icon was not changed afterwards.

### :scroll: Pubspec.yaml


My [pubspec.yaml](https://github.com/git-akihakune/nextlaunch/blob/feature_layout/nextlaunch/pubspec.yaml)

**Comment by zyphlar** [comment]
Could this perhaps be in the documentation somewhere? Or at least emit a more accurate error message? I added "minSdk=19" and "flutter.minSdk=19" before googling to find this issue and adding "flutter.minSdkVersion=19" to fix the issue. Say what you mean, mean what you say, etc.

**Comment by WeebNetsu** [comment]
I specified mine in android/app/build.gradle: `minSdkVersion 21` (here: https://github.com/WeebNetsu/4chan-roller/blob/main/android/app/build.gradle#L50)

This is a better way to do it?

**Comment by jakehockey10** [comment]
@WeebNetsu I'm not sure if it is a better way to do it.  I have `minSdkVersion 21` in my build.gradle file and it still didn't work.  I had to add `flutter.minSdkVersion=21` in my local.poperties file for this to work.

**Comment by WeebNetsu** [comment]
@jakehockey10 Are you sure you put it inside the right build.gradle? There are multiple which does make it confusing... Also check cache, what are the the build.gradle was possibly cached? Remember to close the app and completely rerun it (not hot reload) to make sure the changes took place

local.properties doesn't get added to git, so it would not make sense to have to put the minSdkVersion in there

**Comment by jakehockey10** [comment]
@WeebNetsu all that sounds reasonable and correct. Unfortunately I couldn't get it to work as you suggested. So for now I've documented it in our wiki that a file not in source control needs to have this line in it. But I agree it shouldn't have to be this way

**Comment by zyphlar** [comment]
Ah ok so it works when I modify my project's `android/app/build.gradle` to have `android{defaultConfig{minSdkVersion 21}}` which makes me wonder where I should appropriately be setting `flutter.minSdkVersion` if not local.properties

**Comment by BrunoDalI** [comment]
Hello

https://www.youtube.com/watch?v=R9rJmOw-JM8&ab_channel=FlutterCodewithBenji

**Comment by saif-flutter** [comment]
Go to  android/local.properties
and Add it. 
flutter.minSdkVersion=21
