### ISSUE TITLE
ERROR ON flutter pub run flutter_launcher_icons:main

### ISSUE THREAD

**Issue by Tafara-Shumba** [fluttercommunity/flutter_launcher_icons#377]
E:\flutter_projects\Live-Location-Tracker-Flutter-master>flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.3)
  ════════════════════════════════════════════

✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section
pub finished with exit code 1

#flutter pub get is not generating any errors though. How can i get past this?

**Comment by RatakondalaArun** [comment]
You need to create a `flutter_launcher_icons.yaml` file at the root of your project or your `pubspec.yaml` file should contains `flutter_icons` section

You can read about this [configs here](https://github.com/fluttercommunity/flutter_launcher_icons#mag-attributes) 

Here is an example from [`example/`](https://github.com/fluttercommunity/flutter_launcher_icons/tree/master/example) directory using `pubspec.yaml`
https://github.com/fluttercommunity/flutter_launcher_icons/blob/d2c493d4f2c24c195de633a8a3e5a2fada7ebbd0/example/default_example/pubspec.yaml#L15-L24

closing this

**Comment by Tafara-Shumba** [comment]
My pubspec.yaml file is already as the link you provided but i am still
getting the error, thanks for assisting. i have copied it and sent you as
it is, maybe you can see my error.

**Comment by RatakondalaArun** [comment]
Can you try with this `flutter_icons` configs in `pubspec.yaml`

```yaml
flutter_icons:
  android: true
  image_path_android: "assets/logo.jpg"
```

**Comment by Tafara-Shumba** [comment]
Thanks, i have just realized from your last response that it is 'flutter_icons' not 'flutter icons' as was in my pubspec.yaml file. Changed that and my issue was resolved

**Comment by Tafara-Shumba** [comment]
version: 1.0.0+1

analyzer :
  enable-experiment :
    - non-nullable

environment:
  sdk: '>=2.13.0-68.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.6
  location: ^4.4.0
  cloud_firestore: ^2.5.1
  firebase_core: ^1.6.0
  permission_handler: ^9.2.0
  firebase_auth: ^3.3.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter icons:
  android: true
  image_path: "assets/logo.jpg"
