### ISSUE TITLE
duplicate run in README?

### ISSUE THREAD

**Issue by sethladd** [fluttercommunity/flutter_launcher_icons#4]
I see "flutter pub pub run ..." in the README. Is the second "pub" a duplicate?

**Comment by franzsilva** [comment]
For some reason the Flutter pub command only returns values to get packages and publish, the second pub returns all the pub commands like run, etc, etc

**Comment by franzsilva** [comment]
flutter pub -h
![image](https://user-images.githubusercontent.com/5158380/33610533-c8f8e79a-d999-11e7-826b-9f21c37eb919.png)
flutter pub pub
![image](https://user-images.githubusercontent.com/5158380/33610583-e0a1576a-d999-11e7-9e59-b668de72507a.png)

**Comment by MarkOSullivan94** [comment]
I'll test this when I'm back home tonight

**Comment by sethladd** [comment]
@franzsilva have you tried `flutter pub run flutter_launcher_icons:main` ?

**Comment by franzsilva** [comment]
Yes, but it returns with an error saying that run is not a subcommand of flutter pub

![image](https://user-images.githubusercontent.com/5158380/33632797-cbadc300-d9dc-11e7-857b-865aaf083613.png)

**Comment by sethladd** [comment]
Thanks. I'll open an issue on the flutter tool.
