### ISSUE TITLE
Fix issue where example is not showing on pub.dev

### ISSUE THREAD

**Issue by MarkOSullivan94** [fluttercommunity/flutter_launcher_icons#402]
Currently pub.dev is not showing any of the flutter_launcher_icon examples, this should be fixed to make it easier for anyone trying out flutter_launcher_icons for the first time

<img width="815" alt="Screenshot 2022-08-08 at 12 57 29" src="https://user-images.githubusercontent.com/6950843/183342496-b221e028-bc50-4604-81fc-30784f72fd92.png">

Source: [pub.dev](https://pub.dev/packages/flutter_launcher_icons/score)

See: [Info on examples](https://dart.dev/tools/pub/package-layout#examples)

**Comment by RatakondalaArun** [comment]
Since `fli` is more a tool than a package, I suggest we add the `example.md` file and proved links to these example directories.
