### ISSUE TITLE
Github page update

### ISSUE THREAD

**Issue by Francesco-FL** [fluttercommunity/flutter_launcher_icons#408]
On the pub.dev page it says to run "flutter pub run flutter_launcher_icons:main" which works fine.

On the Github page, on the other hand, the ":main" is not shown and it doesn't work.

![Immagine 2022-08-21 152703](https://user-images.githubusercontent.com/83022092/185793363-db08b37e-b219-4a4f-885c-aaf34dba0858.png)

**Comment by RatakondalaArun** [comment]
The change is not yet released to pub.dev

**Comment by Francesco-FL** [comment]
Ah okay
