### ISSUE TITLE
[BUG] IT CREATES A Splash screen with the icon

### ISSUE THREAD

**Issue by tluanga** [fluttercommunity/flutter_launcher_icons#409]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

The package generate a splash screen using the icon asset

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by RatakondalaArun** [comment]
You can modify splash screen with [flutter_native_splash](https://pub.dev/packages/flutter_native_splash)

Closing this as out of scope
