### ISSUE TITLE
Rename key in pubspec to `flutter_launcher_icons`

### ISSUE THREAD

**Issue by bartekpacia** [fluttercommunity/flutter_launcher_icons#415]
### :speech_balloon: Description

I'd like the key in `pubspec.yaml` that is used to configure this plugin to be renamed. Currently it's named `flutter_icons`, which is kinda misleading, especially that there's a [flutter_icons package on pub.dev](https://pub.dev/packages/flutter_icons).

I'd like the key to be renamed to `flutter_launcher_icons`. This would be a small yet breaking change, but I think it's worth doing to cause less confusion.

**Comment by RatakondalaArun** [comment]
We are planning to introduce a new scheme for the flutter_launcher_icons config file #373

We can add this to that tracker.

**Comment by bartekpacia** [comment]
Oh, that's great. The new config scheme looks much better. I'd really appreciate adding this issue to that tracker :) It's going to be a breaking change anyway.

**Comment by MarkOSullivan94** [comment]
@bartekpacia this should be available in v0.13.1
