### ISSUE TITLE
Documentation improvement: Path on MacOS

### ISSUE THREAD

**Issue by under3415** [fluttercommunity/flutter_launcher_icons#422]
When running this on MacOS you need prefix path with `./`. So use:

`image_path: "./assets/icon/icon.png"`

instead of:

`image_path: "assets/icon/icon.png"`

If you use the path syntax from the documentation you will get below error:

> ✕ Could not generate launcher icons
> FileSystemException: Cannot open file, path = 'assets/icon/icon.png' (OS Error: No such file or directory, errno = 2)
> pub finished with exit code 2

**Comment by jpdup** [comment]
When is version 0.11 going to be published?
