### ISSUE TITLE
[BUG] Dart 2.13.0 is incompatible

### ISSUE THREAD

**Issue by moradnajem** [fluttercommunity/flutter_launcher_icons#427]
error ---> Dart 2.13.0 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (1 year, 5 months ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

i'm using launcher icons version
flutter_launcher_icons: ^0.10.0

**Comment by MarkOSullivan94** [comment]
Thanks for the report @moradnajem, I've just published v0.11.0, please try this and let me know if it fixes your issue.
