### ISSUE TITLE
Generation produces newline diff in Manifest and Project file

### ISSUE THREAD

**Issue by hofbi** [fluttercommunity/flutter_launcher_icons#43]
After running the command to generate the icons I get this diff in `AndroidManifest.xml`and `project.pbxproj`

```
-}
+}
\ No newline at end of file
```

Most editors add by default a newline at the end of a file. To avoid such unnecessary diff it would be nice if the tool cold also add a newline at EOF.

**Comment by MarkOSullivan94** [comment]
@hofbi not entirely sure I understand. If I add a newline at the end of the file, this wont come up as a diff?

**Comment by MarkOSullivan94** [comment]
Spent time investigating this last night, fixed the `AndroidManifest` issue but will need to spend more time on the `project.pbxproj` issue.

**Comment by MarkOSullivan94** [comment]
This will be fixed in the next release. Thanks for opening this!
