### ISSUE TITLE
Could not find bin/flutter_launcher_icons.dart in package flutter_launcher_icons.

### ISSUE THREAD

**Issue by Kant0505** [fluttercommunity/flutter_launcher_icons#431]
```
$ flutter pub run flutter_launcher_icons
Could not find bin/flutter_launcher_icons.dart in package flutter_launcher_icons.
pub finished with exit code 66

```

**Comment by mikestichling** [comment]
Have you tried 

```
flutter pub get
flutter pub run flutter_launcher_icons:main
```

Notice the `:main` at the end of the second command. Ran into the same issue and found this following solution:

https://github.com/fluttercommunity/flutter_launcher_icons/issues/211#issuecomment-730069883

**Comment by husainazkas** [comment]
same issue but fixed after add :main end of the command. The readme.md was remove :main and this makes us confuse. As you can see in this commit [142a6a](https://github.com/fluttercommunity/flutter_launcher_icons/commit/142a6a703c24d8e375b8038097e1d2bc951ccff1)

**Comment by Elvisthomme** [comment]
> same issue but fixed after add :main end of the command. The readme.md was remove :main and this makes us confuse. As you can see in this commit [142a6a](https://github.com/fluttercommunity/flutter_launcher_icons/commit/142a6a703c24d8e375b8038097e1d2bc951ccff1)

Thank you. It also works for me.

**Comment by MohaDevPro** [comment]
I set config in pubspec.yaml so I tried this below 
```
flutter pub get
flutter pub run flutter_launcher_icons:main
```
but not work to me 


then I tried this below and It's work
```
flutter pub get
flutter pub run flutter_launcher_icons:main - pubspec.yaml
```
