### ISSUE TITLE
Adding launch image / splash screen generation

### ISSUE THREAD

**Issue by hofbi** [fluttercommunity/flutter_launcher_icons#44]
Nice tool for generating the app icons. But it would be very nice if one could also generate the launch images (spalsh screen) as written in [this](https://flutter.io/assets-and-images/#updating-the-launch-screen) section of the flutter docs.

For android just another icon to generate is required. Additionally a `launch_background.xml` file, a color attribute and the xmls filename in `style.xml` is required, but should be quite similar as for the adaptive icons.

For ios it is the same as for the app icon, just another target path.

**Comment by angel1st** [comment]
Any recent updates on the topic? It would be an excellent addition to this awesome package, @MarkOSullivan94

**Comment by josepalbert95** [comment]
Any news on this?

**Comment by guenth39** [comment]
Any update?

**Comment by SimonIT** [comment]
There is a seperate lib for this https://github.com/henriquearthur/flutter_native_splash

**Comment by omerasif57** [comment]
> There is a seperate lib for this https://github.com/henriquearthur/flutter_native_splash

which is incompatible with latest version ( `0.9.0` )
