### ISSUE TITLE
[FEATURE REQUEST] Upgrade image dependency from 3.0.2 to the latest 4.0+

### ISSUE THREAD

**Issue by BirjuVachhani** [fluttercommunity/flutter_launcher_icons#442]
### :speech_balloon: Description
This library prevents me from using the latest dependency of [image library](https://pub.dev/packages/image) in my project since I am using this package and it depends on `image: 3.0.2`.

One of the changelogs of `image: 4.0.0`
```
Major overhaul of the API. Dart has changed a lot in the 10 years since this library was written, so the API has been modernized.
```

See full changelog [here](https://pub.dev/packages/image/changelog).

### :question: Platform
None.

**Comment by GotJimmy** [comment]
Same here. Cannot upgrade my project to Image 4.0.8 because of dependency conflict with this package. Please fix soon :)

**Comment by RoyalCoder88** [comment]
have the same problem:

```
Because no versions of flutter_launcher_icons match >0.11.0 <0.12.0 and flutter_launcher_icons 0.11.0 depends on image ^3.0.2, flutter_launcher_icons ^0.11.0 requires image ^3.0.2.
```

please upgrade it, thanks in advance!

**Comment by geekz-reno** [comment]
> have the same problem:
> 
> ```
> Because no versions of flutter_launcher_icons match >0.11.0 <0.12.0 and flutter_launcher_icons 0.11.0 depends on image ^3.0.2, flutter_launcher_icons ^0.11.0 requires image ^3.0.2.
> ```
> 
> please upgrade it, thanks in advance!

hi, for temp solve, you can refer this fork, https://github.com/geekz-reno/flutter_launcher_icons.git

**Comment by sirwes** [comment]
I also want this upgrade

**Comment by mariopepe** [comment]
I need this too, following

**Comment by ycherniavskyi** [comment]
This issue was resolved by https://github.com/fluttercommunity/flutter_launcher_icons/pull/447.

**Comment by MarkOSullivan94** [comment]
As pointed out by @ycherniavskyi this is now resolved, thank you @BirjuVachhani for your contribution!
