### ISSUE TITLE
Please upgrade dependencies

### ISSUE THREAD

**Issue by KristijanZic** [fluttercommunity/flutter_launcher_icons#449]
Please upgrade dependencies. Namely the `image` dependency because it conflicts with other packages like `flutter_native_splash`.

Thanks!

**Comment by fredmo** [comment]
idem :

Because no versions of flutter_launcher_icons match >0.11.0 <0.12.0 and flutter_launcher_icons 0.11.0 depends on image ^3.0.2, flutter_launcher_icons ^0.11.0 requires image ^3.0.2.
And because flutter_native_splash >=2.2.17 depends on image ^4.0.10, flutter_launcher_icons ^0.11.0 is incompatible with flutter_native_splash >=2.2.17.

**Comment by pastelcode** [comment]
Same here

**Comment by RoyalCoder88** [comment]
Same here, please update it. Thanks in advance!

**Comment by bozorkom** [comment]
Because flutter_launcher_icons >=0.9.0 <0.9.1 depends on yaml ^3.0.0-nullsafety.0 and flutter_launcher_icons >=0.7.1 <0.9.0 depends on image ^2.1.1, flutter_launcher_icons >=0.7.1 <0.9.1 requires yaml ^3.0.0-nullsafety.0 or image ^2.1.1.
(1) So, because flutter_launcher_icons >=0.4.0 <0.7.1 depends on image ^2.0.0 and flutter_launcher_icons <0.4.0 requires SDK version >=1.20.1 <2.0.0, flutter_launcher_icons <0.9.1 requires yaml ^3.0.0-nullsafety.0 or image ^2.0.0.

    Because flutter_launcher_icons <0.4.0 requires SDK version >=1.20.1 <2.0.0 and flutter_launcher_icons >=0.4.0 <0.7.1 depends on image ^2.0.0, flutter_launcher_icons <0.7.1 requires image ^2.0.0.
    And because flutter_launcher_icons >=0.7.1 <0.9.0 depends on yaml ^2.1.15 and flutter_launcher_icons >=0.9.0 <0.9.1 depends on image ^3.0.0-nullsafety.0, flutter_launcher_icons <0.9.1 requires image ^2.0.0 or ^3.0.0-nullsafety.0 or yaml ^2.1.15.
    And because flutter_launcher_icons <0.9.1 requires yaml ^3.0.0-nullsafety.0 or image ^2.0.0 (1), flutter_launcher_icons <0.9.1 requires image >=2.0.0 <3.0.0 or ^3.0.0-nullsafety.0.
    And because flutter_launcher_icons >=0.9.1 depends on image ^3.0.2, every version of flutter_launcher_icons requires image >=2.0.0 <3.0.0 or >=3.0.0-nullsafety.0 <4.0.0.
    So, because elmarket depends on both image ^4.0.12 and flutter_launcher_icons any, version solving failed.
pub finished with exit code 65

**Comment by urmamb** [comment]
```
Because flutter_launcher_icons 0.11.0 depends on image ^3.0.2 and no versions of flutter_launcher_icons match >0.11.0 <0.12.0, flutter_launcher_icons ^0.11.0 requires image ^3.0.2.
So, because xplug depends on both flutter_launcher_icons ^0.11.0 and image ^4.0.12, version solving failed.
```

Please solve it.

**Comment by eugenio-d-tesio** [comment]
Same here. Please update ASAP!!

**Comment by eugen-auschew** [comment]
Same here. `Because flutter_launcher_icons 0.11.0 depends on image ^3.0.2`
Please upgrade.

**Comment by inkomomutane** [comment]
Some here please update

**Comment by peter100u** [comment]
Same here, please update it. Thanks in advance!

**Comment by inkomomutane** [comment]
@peter100u  
For anyone facing this issue before mergingthis #pr can add it in *.yml:
```
  flutter_launcher_icons:
    git: 
      url: https://github.com/carloshpb/flutter_launcher_icons
```

**Comment by vinurs** [comment]
Same here, please update it. Thanks in advance! @MarkOSullivan94

**Comment by platinaboy2020** [comment]
Same here, please update it. Thanks in advance!

**Comment by mark8044** [comment]
The people demand an update :)

**Comment by LostInDarkMath** [comment]
Same issue here.

**Comment by Martimiz** [comment]
Same issue, an update would be great, thanks :)

**Comment by lucasjbyoung** [comment]
Same issue here

**Comment by RoyalCoder88** [comment]
Hi friends, I just contact the authors via email about this issue, I hope they will fix this asap. 
Happy coding #

**Comment by tuotau-lessonapp** [comment]
It's April and still waiting for an update! Please update this ASAP thanks!

**Comment by MarkOSullivan94** [comment]
@tuotau-lessonapp this is outdated, the latest version already has v4.0.15 of `image` and so closing this

If you are having an issue with a dependency causing a conflict with another package, please open another issue and show which dependencies are causing an issue for you along with the error message
