### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by reinanbr** [fluttercommunity/flutter_launcher_icons#455]
help in it error.

please, update the your package image

host$ flutter pub add flutter_launcher_icons                                                                                                                                                                   (base) 
The current Dart SDK version is 2.18.5.

Because flutter_launcher_icons <0.4.0 requires SDK version >=1.20.1 <2.0.0 and flutter_launcher_icons >=0.4.0 <0.7.1 depends on image ^2.0.0, flutter_launcher_icons <0.7.1 requires image ^2.0.0.
And because flutter_launcher_icons >=0.7.1 <0.9.0 depends on yaml ^2.1.15, flutter_launcher_icons <0.9.0 requires image ^2.0.0 or yaml ^2.1.15.
And because flutter_launcher_icons >=0.9.0 <0.9.1 depends on image ^3.0.0-nullsafety.0 and flutter_launcher_icons >=0.9.1 depends on image ^3.0.2, every version of flutter_launcher_icons requires image ^2.0.0 or >=3.0.0-nullsafety.0 <4.0.0 or yaml ^2.1.15.
And because flutter_native_splash >=2.2.17 depends on image ^4.0.10 and flutter_native_splash >=2.2.0 depends on yaml ^3.1.1, flutter_native_splash >=2.2.17 is incompatible with flutter_launcher_icons.
So, because rocket_app_flutter depends on both flutter_native_splash ^2.2.17 and flutter_launcher_icons any, version solving failed.
pub finished with exit code 65

**Comment by rafaellfx** [comment]
Same here

**Comment by RatakondalaArun** [comment]
Closing this as this issue has been fixed in the latest release 2a9185afb8a2f41e4a994cecfa86bfb9f0a31a6e
