### ISSUE TITLE
[BUG] Please Update Documentation

### ISSUE THREAD

**Issue by timmkent** [fluttercommunity/flutter_launcher_icons#457]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

In the description it says, that you have to run:

flutter pub run flutter_launcher_icons

but in fact you have to run:

flutter pub run flutter_launcher_icons:main

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by OutdatedGuy** [comment]
The `flutter pub run flutter_launcher_icons:main` is deprecated, and `flutter pub run flutter_launcher_icons` is recommended. So the docs are correct.

**Comment by OutdatedGuy** [comment]
@MarkOSullivan94 can you close this issue as an `invalid`

**Comment by kauemurakami** [comment]
try https://pub.dev/packages/icons_launcher
