### ISSUE TITLE
[White space aroound image] 

### ISSUE THREAD

**Issue by Sg323** [fluttercommunity/flutter_launcher_icons#467]
### :information_source: Info
flutter_launcher_icons: ^0.12.0

### :speech_balloon: Description
Android 12 miui 13 image not fill lcon
the icon has white space all around it

### :scroll: Pubspec.yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  background_color: "#000000"
  min_sdk_android: 21

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by WasaLordy** [comment]
Hi Sg323,
I faced the same problem now.
This video helped me to get rid of this space around the real icon: https://www.youtube.com/watch?v=eMHbgIgJyUQ
I used this tool to generate my new icon: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
"Foreground" --> "Image" --> select from device --> adjust "Padding" --> click "Download Zip"

I hope I could help.

**Comment by erperejildo** [comment]
> Hi Sg323, I faced the same problem now. This video helped me to get rid of this space around the real icon: https://www.youtube.com/watch?v=eMHbgIgJyUQ I used this tool to generate my new icon: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html "Foreground" --> "Image" --> select from device --> adjust "Padding" --> click "Download Zip" It seems to be necessary to create an adaptive_icon_foreground...
> 
> I hope I could help.

so what's this package for then?

**Comment by MarkOSullivan94** [comment]
The new inset configuration should help with this
