### ISSUE TITLE
[BUG] please correct my pubspec file i am changing logo icon of app in terminal it showing The term 'flutter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the  path is correct and try again.

### ISSUE THREAD

**Issue by chirag-GJ13** [fluttercommunity/flutter_launcher_icons#469]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

[](url)
### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by OutdatedGuy** [comment]
You have not added flutter binary as path variable to execute the command in terminal.

Follow the steps mentioned in the original documentation for the platform you are using:

*Windows:* https://docs.flutter.dev/get-started/install/windows#update-your-path

*macOS:* https://docs.flutter.dev/get-started/install/macos#update-your-path

*Linux:* https://docs.flutter.dev/get-started/install/linux#update-your-path

**Comment by OutdatedGuy** [comment]
@MarkOSullivan94 can you close this issue as an `invalid`

**Comment by chirag-GJ13** [comment]
Done
