### ISSUE TITLE
[BUG] Error: No pubspec.yaml file found. This command should be run from the root of your Flutter project.

### ISSUE THREAD

**Issue by yamatestop15** [fluttercommunity/flutter_launcher_icons#470]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by OutdatedGuy** [comment]
@yamatestop15 you have to open the terminal window at the root of your project.

i.e. the `cd path_to_project_root_dir` and then run the command `flutter pub run flutter_launcher_icons`

**Comment by Aashish2050s** [comment]
Error: No pubspec.yaml file found.

This command should be run from the root of your Flutter project.
 Solv कोडिङ दिनु न
