### ISSUE TITLE
Could not find a file named "pubspec.yaml"

### ISSUE THREAD

**Issue by bygrace1986** [fluttercommunity/flutter_launcher_icons#50]
I just added `flutter_launcher_icons` and when I run `flutter pub get` I get the following output:

```
Could not find a file named "pubspec.yaml" in https://github.com/MarkOSullivan94/dart_config.git 5ab9e70727d858def3a586db7fb98ee580352957.
pub get failed (1)
```

This prevents me from using the plugin. I am on the flutter beta channel v0.8.2.

**Comment by aaronfg** [comment]
Same issue here.

```
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.0)
[✓] Connected device (2 available)

```

**Comment by aaronfg** [comment]
FYI I fixed this on my machine by manually repairing the cache.

Run this:
`flutter pub pub cache repair`

then i re-ran:
`flutter packages get`
and
`flutter packages pub run flutter_launcher_icons:main`

That seemed to do the trick.

**Comment by MarkOSullivan94** [comment]
@bygrace1986 if that works for you I'll close this issue

**Comment by w4mxl** [comment]
@MarkOSullivan94  Same issue here. 
And @aaronfg  way also doesn't work for me 🙁
My flutter version: 1.0.0+1

**Comment by w4mxl** [comment]
I just solved this by myself.

Before , when I run `flutter packages get`  I get the following output:
`Could not find a file named "pubspec.yaml" in https://github.com/MarkOSullivan94/dart_config.git 7a88fbc5fd987dce78e468ec45e9e841a49f422d.`

Then, I deleted the folder **git** under --/flutter/.pub-cache/ , then `flutter packages get` works.

Hope this works for others too～

**Comment by MarkOSullivan94** [comment]
Thanks for sharing @w4mxl! 

The more solutions posted here, the less likely someone will get stuck with the same issue. Appreciate everyone posting how they fixed this issue.

**Comment by dmvvilela** [comment]
None of these worked for me.. ;/

**Comment by flushentitypacket** [comment]
@w4mxl That didn't work for me, but it pointed me in the right direction.

For some reason, flutter seemed to be looking at `/Users/myusername/.pub-cache/git` whereas the files were living in `/Users/myusername/flutter/.pub-cache/git`. I'm not sure why that would be the case, but I solved my problem by symlinking `ln -s /Users/myusername/flutter/.pub-cache /Users/myusername/.pub-cache`. Hopefully this helps someone. (Also, if someone has a better solution than this hack, that would be much appreciated.)

**Comment by illvart** [comment]
> @w4mxl That didn't work for me, but it pointed me in the right direction.
> 
> For some reason, flutter seemed to be looking at `/Users/myusername/.pub-cache/git` whereas the files were living in `/Users/myusername/flutter/.pub-cache/git`. I'm not sure why that would be the case, but I solved my problem by symlinking `ln -s /Users/myusername/flutter/.pub-cache /Users/myusername/.pub-cache`. Hopefully this helps someone. (Also, if someone has a better solution than this hack, that would be much appreciated.)

Yes, same problem, solved by symlinking.

**Comment by takiuddin93** [comment]
> I just solved this by myself.
> 
> Before , when I run `flutter packages get` I get the following output:
> `Could not find a file named "pubspec.yaml" in https://github.com/MarkOSullivan94/dart_config.git 7a88fbc5fd987dce78e468ec45e9e841a49f422d.`
> 
> Then, I deleted the folder **git** under --/flutter/.pub-cache/ , then `flutter packages get` works.
> 
> Hope this works for others too～

This worked for me, thanks a lot!

**Comment by YoumingLiu1** [comment]
> 

Hi guys,I am facing the same issue in Android studio and I tried your solution,but when I run “flutter packages get”，I was asked "how do your want to open this file ", still didnt work...
