### ISSUE TITLE
[Provide a Dark and Light Theme Icon]

### ISSUE THREAD

**Issue by HaroonRehman** [fluttercommunity/flutter_launcher_icons#502]
### :speech_balloon: Description
A clear and concise description of what you would like to be added to Flutter Launcher Icons.

### :question: Platform
Is this feature request for a specific platform? E.g. Web / iOS / Android / Mac OS / Windows / Linux

I need to have different icon when the system is in dark mode , and different icon when the system is in light mod

**Comment by hamzament** [comment]
Any updates on this?

**Comment by arabnology** [comment]
Still nothing here...

**Comment by MarkOSullivan94** [comment]
This is now available for iOS

**Comment by mohadel92** [comment]
@MarkOSullivan94  what about android any native way ?

**Comment by mohadel92** [comment]
@MarkOSullivan94  what about android any native way ?
