### ISSUE TITLE
How do you change the iOS app icon background color during launch animation?

### ISSUE THREAD

**Issue by A-REDA-EL** [fluttercommunity/flutter_launcher_icons#503]
When launching a flutter built iOS application, I briefly get this black background surrounding the launch screen. How would you change the black background depicted in the image? I tried changing the launch screen background color in Xcode, but I still get this black "border".

![oojjTm](https://github.com/fluttercommunity/flutter_launcher_icons/assets/72277960/eb892cf6-2993-4c12-8768-7552d97738b3)

![Jm1mCm](https://github.com/fluttercommunity/flutter_launcher_icons/assets/72277960/0d82ce2d-d583-41c7-ac5d-aa9a0afc2db0)

![zFvFEm](https://github.com/fluttercommunity/flutter_launcher_icons/assets/72277960/9947aca0-27f3-4863-b266-9d61abc60c63)

![289AKm](https://github.com/fluttercommunity/flutter_launcher_icons/assets/72277960/5096b6f6-041c-4d58-a770-4df53d6843f7)

**Comment by emirariemir** [comment]
It looks like there's some kind of a **preview of your app showing up and scaling within a second**. That black background might be the background blur in your app but at the start, it looks so blurry that it turns into complete black. At least thats what I see from the images you provided. Have you tried launching your app with another view, with a different background and different elements? Maybe that's the issue.

**Comment by ezhulkov** [comment]
I have the same issue when user swipes to home screen and application is minimized to the icon. Rectangular window of the application is squeezing to square icon and iOS draws white background for missing area  

<img width="585" height="1266" alt="Image" src="https://github.com/user-attachments/assets/8995c059-1fc4-49f2-b8ee-690f20cdfdfe" />
