### ISSUE TITLE
PathNotFoundException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png' (OS Error: The system cannot find the path specified. , errno = 3)[BUG] 

### ISSUE THREAD

**Issue by ratankumarthakur** [fluttercommunity/flutter_launcher_icons#518]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by noblesseobl** [comment]
did you resolved it?

**Comment by vlts1** [comment]
I was getting the same error when building an ipa, here is how I resolved it:

1. Go into the ios folder, and click on Runner.xcworkspace to open the Flutter project in Xcode.
2. In Xcode, toggle the blue icon with Runner, inside of it there is another folder named Runner, open it too.
3. Click on Assets. Then you will see that your icon set is named AppIcon. Copy it, and name the copy LaunchImage. If LaunchImage already exists and it's empty, simply delete it and proceed to rename. 
4. Now, rebuild your project, the error should go away.
