### ISSUE TITLE
incorrectly named icons for Android

### ISSUE THREAD

**Issue by thirddimensionstudios** [fluttercommunity/flutter_launcher_icons#52]
Version: 0.6.1
Dart + Flutter: latest release as of 16/10/2018

When running flutter pub pub run flutter_launcher_icons:main on a new project the icons are copied and named 'true,.png' and the AndroidManifest.xml is also amended to reflect this name. 

Resources cannot contain comma's so this causes a build error. Renaming the icons and correcting the AndroidManifest fixes the issue.

**Comment by MarkOSullivan94** [comment]
Hi @thirddimensionstudios  thanks for the report.

To help fix this issue could you post your pubspec.yaml?

**Comment by MarkOSullivan94** [comment]
@thirddimensionstudios remove the comma after the true for both `android` and `ios` field. That should fix your issue :)

**Comment by thirddimensionstudios** [comment]
Must have been in dart mode when I wrote those lines - thanks!
