### ISSUE TITLE
Incorrect Configuration in README 

### ISSUE THREAD

**Issue by sepehrTabeian** [fluttercommunity/flutter_launcher_icons#523]
Hi there,

I hope this message finds you well. I have identified a mistake in the README file for the "flutter_launcher_icons" repository on GitHub. The issue lies in the configuration section where the Android launcher icon setting is incorrectly labeled. Here's the correct structure that should be used:
```
flutter_icons:
  android: "launcher_icon"
```

The current README incorrectly states:

```
flutter_launcher_icons:
   android: "launcher_icon"
```
I recommend updating the README with the accurate configuration structure to avoid any confusion for developers using the "flutter_launcher_icons" package.

Thank you for maintaining this project, and I appreciate your attention to this matter.

Best regards,
Sepehr
GitHub: [SepehrTabeian](https://github.com/sepehrTabeian)

**Comment by droidbg** [comment]
@sepehrTabeian ig flutter_icons is now changed to flutter_launcher_icons.

Reference: https://github.com/fluttercommunity/flutter_launcher_icons/issues/415
PR: https://github.com/fluttercommunity/flutter_launcher_icons/pull/479/files

**Comment by sepehrTabeian** [comment]
Yes, Thank you @droidbg
