### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Blacksheep70** [fluttercommunity/flutter_launcher_icons#525]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

PathNotFoundException , no matter where I put the file

```
`PS D:\Documents\Coding\BikerBuddy\bikerbuddy> dart run flutter_launcher_icons -v
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

[     0.000s] Received args [-v]
• Creating default icons Android

✕ Could not generate launcher icons
PathNotFoundException: Cannot open file, path = 'assets/icon_a.png' (OS Error: System could not find the specified file., errno = 2)
PS D:\Documents\Coding\BikerBuddy\bikerbuddy>`
```

The file icon_a.png is residing in <project root>/assets/icon_a.png

```
` Directory of D:\Documents\Coding\BikerBuddy\bikerbuddy\assets

13.10.2023  10:16    <DIR>          .
13.10.2023  10:33    <DIR>          ..
10.10.2023  12:54            23.924 erika.png
10.10.2023  12:56            28.655 john.png
11.10.2023  06:36           615.666 logo.png
13.10.2023  10:16             3.254 logo_a.png
10.10.2023  12:55            17.493 max.png
               5 Datei(en),        688.992 Bytes
               2 Verzeichnis(se), 66.072.928.256 Bytes frei`
```

Tree output
[tree.txt](https://github.com/fluttercommunity/flutter_launcher_icons/files/12892399/tree.txt)

### :scroll: Pubspec.yaml
[pubspec.yaml.txt](https://github.com/fluttercommunity/flutter_launcher_icons/files/12892408/pubspec.yaml.txt)

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by ManuelRauber** [comment]
@Blacksheep70 According to your log output from the file tree, there is no `icon_a.png` but a `logo_a.png`.
