### ISSUE TITLE
[BUG] Could not find a file named "pubspec.yaml"

### ISSUE THREAD

**Issue by pascal220** [fluttercommunity/flutter_launcher_icons#544]
### Info
Version: `e.g. v0.13.1`

###Description
I am getting the following error:
Could not find a file named "pubspec.yaml" in "C:\Users\XXXXX\AppData\Local\Pub\Cache\hosted\pub.dev\file_selector_linux-0.9.2+1".
I am running the project on Windows 11, through VS Code.

###Pubspec.yaml
name: XXXXX
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  uuid: ^4.3.3
  flutter_riverpod: ^2.4.10
  image_picker: ^1.0.7
  location: ^5.0.3
  http: ^1.1.0
  google_maps_flutter: ^2.5.3
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/XXXXX.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

**Comment by MarkOSullivan94** [comment]
Sounds like you need to run `flutter pub get`
