### ISSUE TITLE
Dart 2.18.2 is incompatible

### ISSUE THREAD

**Issue by tameralgul** [fluttercommunity/flutter_launcher_icons#548]
Dart 2.18.2 is incompatible with your dependencies' SDK constraints. Please run "flutter pub get" again.
pub finished with exit code 65

flutter 3.19.3
dart 3.3.1

flutter_launcher_icons: ^0.13.1

thanks,

**Comment by MarkOSullivan94** [comment]
I've updated to use a newer version of Dart in v0.14.0
