### ISSUE TITLE
[BUG] Adaptive Monochrome Icons are not generated

### ISSUE THREAD

**Issue by MatthewRiley05** [fluttercommunity/flutter_launcher_icons#555]
### :information_source: Info

Version: `e.g. v0.13.1`

### :speech_balloon: Description

Adaptive icon foreground, background, and monochrome are all supplied and indicated in the .yaml file but the Material You monochrome icon does not work at all when using the color palette for app icons. The device used is a Samsung Galaxy S22 Ultra running OneUI 6.0. It seems that even if adaptive_icon_monochrome is included in the pubspec.yaml, these icons are not generated and distributed to the res folders.

### :scroll: Pubspec.yaml

name: qr_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  share: ^2.0.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
      - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf

flutter_launcher_icons:
  image_path_android: "assets/icons/QR_Generator_Icon.png"
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/QR_Generator_Icon_Foreground.png"
  adaptive_icon_monochrome: "assets/icons/QR_Generator_Icon_Monochrome.png"
  min_sdk_android: 21

**Comment by coyotte508** [comment]
It's not released. See https://github.com/fluttercommunity/flutter_launcher_icons/pull/497#issuecomment-2010358962

**Comment by B-l-u-e-f-i-r-e** [comment]
Why is it not released? Is there any reason why this should not be able to release?

**Comment by MarkOSullivan94** [comment]
This is fixed now as of v0.14.0
