### ISSUE TITLE
[BUG] Icon not updated

### ISSUE THREAD

**Issue by viktorsht** [fluttercommunity/flutter_launcher_icons#558]
Update the icon with the command

But the icon is not updated in the app.

Command
flutter pub run flutter_launcher_icons

Version:
flutter_launcher_icons: ^0.13.1

Pubspec.yaml
flutter_launcher_icons:
     image_path: "assets/icon/icon.png"
     android: "launcher_icon"
     apaptive_icon_background: "#ffffff"
     apaptive_icon_foreground: "assets/icon/icon.png"

**Comment by Anas-jed** [comment]
Same issue, Any updates? @viktorsht

**Comment by viktorsht** [comment]
Comrade, I made the icon in the traditional way using the video https://www.youtube.com/watch?v=7ICS-PYjJfI

**Comment by MarkOSullivan94** [comment]
> Update the icon with the command
> 
> But the icon is not updated in the app.
> 
> Command flutter pub run flutter_launcher_icons
> 
> Version: flutter_launcher_icons: ^0.13.1
> 
> Pubspec.yaml flutter_launcher_icons: image_path: "assets/icon/icon.png" android: "launcher_icon" apaptive_icon_background: "#ffffff" apaptive_icon_foreground: "assets/icon/icon.png"

You spelt **adaptive** wrong in your configuration
