### ISSUE TITLE
[BUG] Could not add icon. 

### ISSUE THREAD

**Issue by sadman017** [fluttercommunity/flutter_launcher_icons#562]
### :information_source: Info

v0.13.1
Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here
Unhandled exception:

✗ ERROR: NoConfigFoundException
No configuration found in flutter_launcher_icons.yaml or in pubspec.yaml. In case file exists in different directory use --file option
#0      createIconsFromArguments (package:flutter_launcher_icons/main.dart:84:7)
#1      main (file:///C:/Users/Sadman%20Rahman%20Ananta/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_launcher_icons-0.13.1/bin/flutter_launcher_icons.dart:7:26)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

### :scroll: Pubspec.yaml

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by MarkOSullivan94** [comment]
Without `pubspec.yaml` I cannot help you
