### ISSUE TITLE
Update image package dependency version to avoid depending on a vulnerable version of the archive package

### ISSUE THREAD

**Issue by notsag-dev** [fluttercommunity/flutter_launcher_icons#571]
### :information_source: Info
Version: `e.g. v0.13.1`

### :speech_balloon: Description
The image version this package depends on right now (4.0.15) depends on a vulnerable version of the `archive` package:

├── flutter_launcher_icons 0.13.1
│   ├── image 4.0.17
│   │   ├── archive 3.3.7

Dependencies are affected by security advisories:
[https://github.com/advisories/GHSA-9v85-q87q-g4vg](https://github.com/advisories/GHSA-9v85-q87q-g4vg)
[https://github.com/advisories/GHSA-r285-q736-9v95](https://github.com/advisories/GHSA-r285-q736-9v95)

**Comment by MarkOSullivan94** [comment]
Thanks for the recommendation
