### ISSUE TITLE
[BUG] Could not find bin\flutter_launcher_icons.dart in package flutter_launcher_icons.

### ISSUE THREAD

**Issue by nguyenphong0612** [fluttercommunity/flutter_launcher_icons#574]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by nguyenphong0612** [comment]
Could not find bin\flutter_launcher_icons.dart in package flutter_launcher_icons.

**Comment by MarkOSullivan94** [comment]
Unless you share, at the very least your project `pubspec.yaml` file I cannot help
