### ISSUE TITLE
All black Icon

### ISSUE THREAD

**Issue by wetdino21** [fluttercommunity/flutter_launcher_icons#589]
It always solid plain black icon

**Comment by AntonioPavkovic** [comment]
> It always solid plain black icon

same for me but only on Android... on iOS works fine

**Comment by PurplePolyhedron** [comment]
See https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554
Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.

**Comment by AntonioPavkovic** [comment]
> 0.13.1

it worked thanks :)

**Comment by AntonioPavkovic** [comment]
> See [#578 (comment)](https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554) Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.
It worked thanks :)

**Comment by SamuelKiragu** [comment]
Thank you. This worked

> See [#578 (comment)](https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554) Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.

Thank you. This worked for met too

**Comment by asadwaheed1** [comment]
> See [#578 (comment)](https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554) Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.

Thank you. This is the working solution for black icon issue on 0.14.1

**Comment by soufrabi** [comment]
> See [#578 (comment)](https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554) Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.

Thanks it worked for me.

**Comment by alishahzad331** [comment]
Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.



> See [#578 (comment)](https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554) Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.

Thanks. It worked

**Comment by hayatbangash55** [comment]
same issue black icon

**Comment by wrteam-vimal** [comment]
![image](https://github.com/user-attachments/assets/3bef207b-9987-4e17-ad20-efe30ad090ff)

Just remove mipmap-anydpi-v26 folder it will most probably solve your issue

Thank you!

**Comment by HC-miss** [comment]
Thanks. It worked

> ![image](https://private-user-images.githubusercontent.com/71313780/374434342-3bef207b-9987-4e17-ad20-efe30ad090ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjk3NTUsIm5iZiI6MTcyODM2OTQ1NSwicGF0aCI6Ii83MTMxMzc4MC8zNzQ0MzQzNDItM2JlZjIwN2ItOTk4Ny00ZTE3LWFkMjAtZWZlMzBhZDA5MGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA2MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMmZiNWQ2OTRmOTk3ZjIxOGFjNWM3ZjQ2M2UxZDUzYmI2MGY0MmE0OWE4M2E5YWY4MTJiZDE5NDA4ZmI5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tLARP-DUNayHaqZaYSuQQezApzPzGiumKcARM0AyfRk)
> 
> Just remove mipmap-anydpi-v26 folder it will most probably solve your issue
> 
> Thank you!

Thanks. It worked

**Comment by HC-miss** [comment]
> ![image](https://private-user-images.githubusercontent.com/71313780/374434342-3bef207b-9987-4e17-ad20-efe30ad090ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjk3NTUsIm5iZiI6MTcyODM2OTQ1NSwicGF0aCI6Ii83MTMxMzc4MC8zNzQ0MzQzNDItM2JlZjIwN2ItOTk4Ny00ZTE3LWFkMjAtZWZlMzBhZDA5MGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA2MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMmZiNWQ2OTRmOTk3ZjIxOGFjNWM3ZjQ2M2UxZDUzYmI2MGY0MmE0OWE4M2E5YWY4MTJiZDE5NDA4ZmI5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tLARP-DUNayHaqZaYSuQQezApzPzGiumKcARM0AyfRk)
> 
> Just remove mipmap-anydpi-v26 folder it will most probably solve your issue
> 
> Thank you!

Thanks. It worked

**Comment by AnssGul** [comment]
> ![image](https://private-user-images.githubusercontent.com/71313780/374434342-3bef207b-9987-4e17-ad20-efe30ad090ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzM0ODYsIm5iZiI6MTcyODM3MzE4NiwicGF0aCI6Ii83MTMxMzc4MC8zNzQ0MzQzNDItM2JlZjIwN2ItOTk4Ny00ZTE3LWFkMjAtZWZlMzBhZDA5MGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA3Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NmM3ZGU1NmY0MGM0MjAwMTBiOWNiZjg4YzlkMDM1YjYxYjFiZWVhOGE0OTM2MWNiMTdkZGQxYTM4MDU3ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TXatgbWe49Syqi_zftgZFw2fCFlsXGkK40Qam3-uQBk)
> 
> Just remove mipmap-anydpi-v26 folder it will most probably solve your issue
> 
> Thank you!

its working  after deleting  mipmap-anydpi-v26 folder on real devicw but in the emulator its not covering all the space of app icon.

**Comment by MarkOSullivan94** [comment]
> See [#578 (comment)](https://github.com/fluttercommunity/flutter_launcher_icons/issues/578#issuecomment-2366797554) Downgrade to version 0.13.1 and delete `android/app/src/main/res/mipmap-anydpi-v26` directory worked for me.

You shouldn't need to downgrade.

If you are experiences this, please try deleting the `android/app/src/main/res/mipmap-anydpi-v26` directory which has fixed this for many.
