### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [fluttercommunity/flutter_launcher_icons#59]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by MarkOSullivan94** [comment]
Never really considered having a logo / icon for the project but if you want to try and design one for free I'd happily consider it

**Comment by MarkOSullivan94** [comment]
It's a unique icon and would definitely stand out (definitely does in your screenshot of the device) however I'm not sure if it's right for this project.

Perhaps something like [the Flutter logo](https://alexisvt.gallerycdn.vsassets.io/extensions/alexisvt/flutter-snippets/0.0.2/1529817162825/Microsoft.VisualStudio.Services.Icons.Default) on a [spaceship](https://cdn.dribbble.com/users/63173/screenshots/3608387/launchpad_icon.png)?

**Comment by mansya** [comment]
How about this ? do you like it ?
![flutter launcher icons](https://user-images.githubusercontent.com/33461607/47893605-53f4a900-de90-11e8-8194-50106ef5e7ef.png)

**Comment by MarkOSullivan94** [comment]
Thanks for submitting the icon however this project isn't actually an application, it's only meant to be used as a tool to help those creating their own Flutter applications, so I think these icons would be better suited to another project.
