### ISSUE TITLE
Black icon.

### ISSUE THREAD

**Issue by theahmedhany** [fluttercommunity/flutter_launcher_icons#594]
The icon is always viewed solid plain black icon.

**Comment by theahmedhany** [comment]
After searching I think the root cause is the file: android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml with content

<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
</adaptive-icon>

is being generated although nothing is configured regarding the adaptive icons.

Deleting this file "mipmap-anydpi-v26" after generating resolves the issue for me.

**Comment by sunny0092** [comment]
> After searching I think the root cause is the file: android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml with content
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
> </adaptive-icon>
> ```
> 
> is being generated although nothing is configured regarding the adaptive icons.
> 
> Deleting this file "_mipmap-anydpi-v26_" after generating resolves the issue for me.

Thanks you
