### ISSUE TITLE
App Icon in android becoming pitch black

### ISSUE THREAD

**Issue by praneshp1org** [fluttercommunity/flutter_launcher_icons#608]
### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: 
  ios: 
  image_path: 
```

Even after successful generation of the icons, the icons in my android is still black.

p1@Pranesh's Macbook Air white_label_code % dart run flutter_launcher_icons
Building package executable... 
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.14.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Adding a new Android launcher icon
• Creating mipmap xml file Android
• Overwriting default iOS launcher icon with new icon
No platform provided

✓ Successfully generated launcher icons
p1@Pranesh's Macbook Air white_label_code %

**Comment by praneshp1org** [comment]
![image](https://github.com/user-attachments/assets/a2839dd6-fe55-4993-832e-5347b879b6ae)

Removing mipmap-anydpi-v26 folder it will most probably solve your issue.

**Comment by dpaniagua0** [comment]
So if the solution is just to remove  that folder, but is this going to have other impact after the folder is deleted?

**Comment by praneshp1org** [comment]
> So if the solution is just to remove that folder, but is this going to have other impact after the folder is deleted?

for me, it didn't have any impact :)
