### ISSUE TITLE
NoSuchMethodError: The getter 'width' was called on null.

### ISSUE THREAD

**Issue by ilkintacan** [fluttercommunity/flutter_launcher_icons#66]
Hello,
I have change my icon png file and rerun below command. How can I correct this error?
Regards.

>flutter packages pub run flutter_launcher_icons:main
Android minSdkVersion = 16
Creating default icons Android
Adding a new Android launcher icon
NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
pub finished with exit code 2

**Comment by MarkOSullivan94** [comment]
Thanks for reporting this issue! 

Could you copy and paste your config file?

**Comment by MarkOSullivan94** [comment]
Sounds like it could be a problem with the image itself. 

Have you tried a different image?

Have you definitely got the image located in the `assets` directory and it's named `icon.png`?

**Comment by ilkintacan** [comment]
Yes, after I've changed image it is working well.
Please add your warning message also this possibility.
Best Regards.
