### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dennmat** [fluttercommunity/flutter_launcher_icons#68]
Can't install the app getting 
`Git error. Command: git clone --mirror https://github.com/MarkOSullivan94/dart_config.git C:\code\flutter\.pub-cache\git\cache\dart_config-d2db83fa92bb229094789c5489c5e2d3cc175814
Cloning into bare repository 'C:\code\flutter\.pub-cache\git\cache\dart_config-d2db83fa92bb229094789c5489c5e2d3cc175814'...
fatal: unable to access 'https://github.com/MarkOSullivan94/dart_config.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

flutter_launcher_icons: "^0.7.0"

I should mention flutter packages get works fine for all other packages I have. So I don't believe it's an issue on my end. Could be wrong though.

**Comment by MarkOSullivan94** [comment]
Is this error appearing after you setup your config file and run the two commands below? 

```
flutter packages get
flutter packages pub run flutter_launcher_icons:main -f <your config file name here>
```

**Comment by dennmat** [comment]
Yes after the config file is setup. But during the `flutter packages get`.

**Comment by dennmat** [comment]
Hey looks like it's a git for windows issue. https://github.com/desktop/desktop/issues/3165

Will close this.

**Comment by MarkOSullivan94** [comment]
Thanks for sharing what caused your issue @dennmat!
