### ISSUE TITLE
 2 unassigned children on iOS

### ISSUE THREAD

**Issue by sestegra** [fluttercommunity/flutter_launcher_icons#73]
1024x1024 icons appear as unassigned in XCode.

**Comment by MarkOSullivan94** [comment]
If these are unassigned and no longer being used we could just remove them in the list of icons to be generated for iOS

**Comment by codegrue** [comment]
These are the ones I get as unassigned:

```
Icon-App-50x50@1x.png
Icon-App-50x50@2x.png
Icon-App-57x57@1x.png
Icon-App-57x57@2x.png
Icon-App-72x72@1x.png
Icon-App-72x72@2x.png
```

**Comment by elmariocarlos** [comment]
> These are the ones I get as unassigned:
> 
> ```
> Icon-App-50x50@1x.png
> Icon-App-50x50@2x.png
> Icon-App-57x57@1x.png
> Icon-App-57x57@2x.png
> Icon-App-72x72@1x.png
> Icon-App-72x72@2x.png
> ```

I can confirm this is currently happening; you can remove them using Xcode, but if not then this is not visible for users relying in a CD/CI just for iOS.
