### ISSUE TITLE
Google will no longer accept images with transparency

### ISSUE THREAD

**Issue by talamaska** [fluttercommunity/flutter_launcher_icons#82]
Please update the plugin to support the new requirement
Source: 
https://www.androidauthority.com/google-play-store-icons-2019-966386

**Comment by MarkOSullivan94** [comment]
Thanks for reporting this. Did some further research and found this.

> Note this does not affect your APK launcher icons for Android.

https://android-developers.googleblog.com/2019/03/introducing-new-google-play-app-and.html
