### ISSUE TITLE
Specify sizes in README

### ISSUE THREAD

**Issue by 12people** [fluttercommunity/flutter_launcher_icons#90]
I'm unclear as to what sizes this plugin requires. Would really appreciate having this info in the README file.

**Comment by MarkOSullivan94** [comment]
Works with any sizes, I think from the tests I've ran I've noticed better quality icons with larger image sizes. 

Feel free to run the example app and try out the different sizes and see which one you think is best.

**Comment by 12people** [comment]
Wonderful, thanks! Was so used to Android accepting only certain sizes, this is a nice breath of fresh air :)

**Comment by rfitz123** [comment]
I followed the steps, but it crops my icon and surrounds it with blank space.
![100iconwrong](https://user-images.githubusercontent.com/54483846/68554180-caf24500-03f4-11ea-9203-aa89f8a3751b.PNG)

**Comment by aoloe** [comment]
the other way round:

- what is the size of the biggest image generated by the tool? (this should be the minimal size for the image)
- which are the proportions of the image? a square?

i had a look at `lib/ios.dart` and `lib/android.dart` and

- android seems to max at 432 and
- ios at 1024

if those numbers are correct, it would be nice to have them in the README.
