### ISSUE TITLE
Android 8.0 does not support it?

### ISSUE THREAD

**Issue by lifetin** [fluttercommunity/flutter_launcher_icons#93]
Android 8.0 does not support it?

![44](https://user-images.githubusercontent.com/10474968/55816193-4ec51580-5b24-11e9-87c2-4cd2d212b29b.png)

**Comment by MarkOSullivan94** [comment]
Try using `adaptive_icon_background` and `adaptive_icon_foreground` for full sized icons on Android 8.0 or greater

See the example project on how to set this up: https://github.com/fluttercommunity/flutter_launcher_icons/tree/master/example

**Comment by mikeroneer** [comment]
@MarkOSullivan94 is this required or an optional feature? I experienced the same issue

**Comment by MarkOSullivan94** [comment]
@mikeroneer if you want to ensure you have full sized icons make sure you use adaptive icons 👍
