### ISSUE TITLE
Error on line 69, column 5 of pubspec.yaml: A dependency may only have one source

### ISSUE THREAD

**Issue by TUKenStone** [fluttercommunity/flutter_launcher_icons#95]

**Comment by MarkOSullivan94** [comment]
Might be an issue with your pubspec.yaml file, would recommend pasting the entire contents and have it formatted correctly so it's easy to spot any formatting issues with your pubspec.yaml

**Comment by kwabenaG** [comment]
Its the issue of your pubspec.yaml file, pasting the whole error code here would me spot  the problem.
