### ISSUE TITLE
Launcher icon

### ISSUE THREAD

**Issue by atilkan** [fluttercommunity/flutter_launcher_icons#97]
You should probably point that this is also generate splash screen.

**Comment by MarkOSullivan94** [comment]
@atilkan do you mean for iOS apps? It changes the icon displayed for the splash screen?

**Comment by atilkan** [comment]
Yes. Laumcher icon and splaah screen should not be generated from the same icon.

**Comment by MarkOSullivan94** [comment]
I believe the default behaviour for _most apps_ is for the launcher icon and splash screen to be the same icon. 

However if you wish to change this, I have seen the splashscreen package recommended: https://pub.dev/packages/splashscreen

**Comment by atilkan** [comment]
No it is not. Thank you anyways.
